function plottingUnits(obj,varargin)
if ~check(obj,'dbg')
    obj.load('Debug');
    obj.dbg.verbosity = Debug.PriorityLevel.ERROR;
end
if ~check(obj,'fg')
    obj.load('Figure');
    obj.fg.overwrite = false;
end
if ~check(obj,'tm')
    obj.load('Time');
    obj.tm.discardpre = 0;
    obj.tm.discardpost = 0;
end
if ~check(obj,'fr')
    obj.load('FiringRate');
    obj.fr.min = 1;
end
if ~check(obj,'spk')
    obj.load('Spike');
    obj.spk.binwidth = 50e-3;
    obj.spk.bin2fr = true;
    obj.spk.fs = 30e3;
    obj.spk.type = 'sorted';
    obj.spk.unsorted = false;
    obj.spk.noise = false;
    obj.spk.timestampunits = 'seconds';
    obj.spk.ratefilt = true;
    obj.spk.ratefiltmethod = 'max';
    obj.spk.ratefiltparams = struct(...
        'mean_threshold',obj.fr.min*obj.spk.binwidth,...
        'mean_bad_fcn',@le,...
        'median_threshold',1,...
        'median_bad_fcn',@le,...
        'max_threshold',1,...
        'max_bad_fcn',@le,...
        'min_threshold',obj.fr.min*obj.spk.binwidth,...
        'min_bad_fcn',@le);
    obj.spk.norm = false;
    obj.spk.normmethod = 'zscore';
    obj.spk.normparams = struct(...
        'percolumn',true,...
        'robust','denominator',...
        'robustmadopts',false,...
        'percentiles',[5 95],...
        'outliercheck',false,...
        'outlierpercol',true,...
        'outlierrep',nan,...
        'outliertiles',[15 85],...
        'outlierthresh',5,...
        'outliersides','both',...
        'denzeropolicy','allow',...
        'denzerorep',true,...
        'regularize','denominator',...
        'regmethod','scale',...
        'regstrength',1.25);
    obj.spk.smooth = true;
    obj.spk.smoothmethod = 'mj';
    obj.spk.smoothparams = struct(...
        'kernelwidth',0.50,...
        'period',obj.spk.binwidth,...
        'halfkernel',true,...
        'causal',true);
end