% This defines the big bus for decoder.slx
% It is hand edited.
% August 2016: Sergey Stavisky changed dimensions of xk and all related
% matrices (e.g. A, C) to be (xkConstants.NUM_STATE_DIMENSIONS instead of
% 5. This is part of our move to highD decoding. Note that the original
% "minimum dimension" matrices (e.g. 5x5 A for 2D Kalman Filter) are still
% saved in the decoder model, under the model.minDim field. These are *not*
% sent into the Simulink Realtime model, because they have no use there.

% STATEVEC_SIZE = 2*double(DecoderConstants.NUM_KINEMATIC_DIMENSIONS)+1;
STATEVEC_SIZE = double(xkConstants.NUM_STATE_DIMENSIONS); % moving towards arbitrary dimensionality SDS
decoderParamsStruct = createTunableStructure('decoder','decoderParameters', 'decoderParams',...
    'filterName', uint8(zeros([1 100])),...
    'discreteFilterName', uint8(zeros([1 100])),...
    'A',double(zeros([STATEVEC_SIZE STATEVEC_SIZE])),...
    'C',double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) STATEVEC_SIZE])),...
    'Cfeedback',double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) STATEVEC_SIZE])),...
    'K',double(zeros([STATEVEC_SIZE double(DecoderConstants.NUM_CONTINUOUS_CHANNELS)])),...
    'dtMS',uint16(50),...
    'thresholds',double(zeros([double(DecoderConstants.NUM_SPIKE_CHANNELS) 1])),...
    'spikeTransform',uint16(DecoderConstants.NO_TRANSFORM),...
    'decoderType',uint16(DecoderConstants.DECODER_TYPE_VFBSSKF),...
    'invSoftNormVals',double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) 1])),...
    'projector',double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) double(DecoderConstants.NUM_CONTINUOUS_CHANNELS)])),...
    'pcaMeans',double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) 1])),...
    'useAcaus',true,...
    'gainK',double(ones([STATEVEC_SIZE 1])),...
    'scaleXk',double(ones([STATEVEC_SIZE 1])),...
    'offsetXk',double(zeros([STATEVEC_SIZE 1])),...
    'hLFPTransform',uint16(DecoderConstants.NO_TRANSFORM),...
    'hLFPDivisor',double(DecoderConstants.HLFP_DIVISOR),...
    'smoothingKernel',[1; zeros([DecoderConstants.MAX_KERNEL_LENGTH-1 1])],...
    'continuousEnable',false,...
    'meansTrackingEnable', false, ...
    'meansTrackingUseFastAdapt', false, ...
    'meansTrackingResetToInitial', false, ...
    'meansTrackingResetToCurrent', false, ...
    'meansTrackingInitial', double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) 1])),...
    'meansTrackingPeriodMS', double(1.5*60*1000),...
    'discreteEnable',false,...
    'discreteInvSoftNormVals',double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) 1])), ...
    'discreteProjector',double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) ...
                                      double(DecoderConstants.MAX_DISCRETE_DECODE_CHANNELS)])), ...
    'discretePcaMeans',double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) 1])), ...
    'hmmNumStates',uint8(1), ... %SNF says wtf shouldn't this be MAX_DISCRETE_STATES? 
    'hmmTrans',double(zeros(double([DecoderConstants.MAX_DISCRETE_STATES ...
                                    DecoderConstants.MAX_DISCRETE_STATES]))), ...
    'hmmEmisMean',double(zeros(double([DecoderConstants.MAX_DISCRETE_STATES ...
                                       DecoderConstants.MAX_DISCRETE_DECODE_CHANNELS]))), ...
    'hmmEmisCovarDet',double(zeros(double([DecoderConstants.MAX_DISCRETE_STATES 1]))), ...
    'hmmEmisCovarInv',double(zeros(double([DecoderConstants.MAX_DISCRETE_STATES ...
                                           DecoderConstants.MAX_DISCRETE_DECODE_CHANNELS ...
                                           DecoderConstants.MAX_DISCRETE_DECODE_CHANNELS]))),...
    'hmmStateModel',uint8(DiscreteStates.STATE_MODEL_MOVECLICK),... %SNF corrected this to use the corresponding macro to uint8(1) because we're not heathens here
    'hmmSpeedScalingEnable', false,...
    'hmmSpeedScalingPs',double(ones(double([DecoderConstants.MAX_DISCRETE_STATES DecoderConstants.NUM_HMM_SPEED_BINS]))), ...
    'hmmSpeedScalingBins',double(zeros(double([DecoderConstants.NUM_HMM_SPEED_BINS 1]))) ...
    );
%    'discreteThresholds',double(zeros([double(DecoderConstants.NUM_SPIKE_CHANNELS) 1])), ...
%    'discreteHLFPTransform',uint16(DecoderConstants.NO_TRANSFORM),...
%    'discreteHLFPDivisor',double(DecoderConstants.HLFP_DIVISOR),...
%    'discreteSmoothingKernel',[1; zeros([DecoderConstants.MAX_KERNEL_LENGTH-1 1])],...
%    'discreteMeansTrackingEnable', false, ...
%    'discreteMeansTrackingUseFastAdapt', false, ...
%    'discreteMeansTrackingResetToInitial', false, ...
%    'discreteMeansTrackingResetToCurrent', false, ...
%    'discreteMeansTrackingInitial', double(zeros([double(DecoderConstants.NUM_CONTINUOUS_CHANNELS) 1])),...
%    'discreteMeansTrackingPeriodMS', double(2*60*1000),...
%    'discreteDtMS',uint16(50), ...
%% decoderOutput Bus
decoderOutput = Simulink.Bus;
decoderOutput.Elements(end+1) = createBusElement('xk', [STATEVEC_SIZE 1], 'double', 'fixed');
decoderOutput.Elements(end+1) = createBusElement('stateLikelihoods', [double(DecoderConstants.MAX_DISCRETE_STATES) 1], 'double', 'fixed');
decoderOutput.Elements(end+1) = createBusElement('clickStateLikelihood', 1, 'double', 'fixed');
decoderOutput.Elements(end+1) = createBusElement('moveStateLikelihood', 1, 'double', 'fixed');