%% model tunable parameters
function taskParamsStruct = fittsTask_buildWorkspace()
taskParamsStruct = createTunableStructure('fittsTask','taskParameters', 'taskParamsBus',...
    'targetDiameters',uint16(repmat(100,[1 fittsConstants.MAX_DIAMETERS])), ...
    'maxTaskTime',uint32(0),...
    'numTargetDiameters',uint16(0),...
    'holdTime',uint16(500),...
    'trialTimeout',uint16(15000),...
    'numTrials',uint16(100),...
    'randomSeed',double(1),...
    'targetDelay',uint16(0),...
    'taskType',uint32(fittsConstants.TASK_FITTS),...
    'gain',double(zeros(1,double(xkConstants.NUM_TARGET_DIMENSIONS)) ),... % SDS August 2016 added third and fourth dimensions
    'failurePenalty',uint16(1000),...
    'cursorDiameter',uint16(30),...
    'inputType',uint16(cursorConstants.INPUT_TYPE_MOUSE_ABSOLUTE),...
    'gloveBias',uint16(zeros([1 5])),...
    'useRandomDelay',uint16(0),...
    'mouseOffset',uint16([0 0]),...
    'workspaceX',double([-500 500]),...
    'workspaceY',double([-500 500]),...
    'workspaceZ',double([-500 500]),...
    'workspaceR',double([-3.142 3.142]),... % rotation bounds
    'recenterOnFail',false,...
    'recenterOnSuccess',false,...
    'recenterDelay',uint16(0),...
    'initialInput',uint16(cursorConstants.INPUT_TYPE_MOUSE_ABSOLUTE),...
    'minTargetDistance',double(0),...
    'targetSpaceX',double([-500 500]),...
    'targetSpaceY',double([-500 500]),...
    'errorAssistR',single( zeros(1, double( xkConstants.NUM_TARGET_DIMENSIONS ) ) ), ...      % slows wrong-direction movement (relative to cursor-target axis) in each dimension separately
    'errorAssistTheta',single( zeros(1, double( xkConstants.NUM_TARGET_DIMENSIONS ) ) ), ...  % attenuates orthogonal component of movement (relative to cursor-target axis) in each dimension separately
    'errorAssistAxis',single( zeros(1, double( xkConstants.NUM_TARGET_DIMENSIONS ) ) ), ...   % New October 2016, attentuates wrong-direction movement (relative to cardinal axes) in each dimension 
    'clickTargetColor',uint8('g'),...
    'clickTargetHoverColor',uint8('b'),...
    'clickPercentage',double(0),...
    'useGloveLPF', false,...
    'gloveLPNumerator', double(zeros(1, 11)), ...
    'gloveLPDenominator', double(zeros(1, 11)), ...
    'useMouseLPF', false,...
    'mouseLPNumerator', double(zeros(1, 11)), ...
    'mouseLPDenominator', double(zeros(1, 11)), ...
    'stopOnClick',true, ...
    'xk2HorizontalPos', uint8(1), ... % SDS July 2016   which state element the game should treat as horizontal position
    'xk2HorizontalVel', uint8(2), ... % SDS July 2016  which state element the game should treat as horizontal velocity
    'xk2VerticalPos', uint8(3), ... % SDS July 2016 which state element the game should treat as vertical position
    'xk2VerticalVel', uint8(4), ... % SDS July 2016  which state element the game should treat as vertical velocity
    'xk2DepthPos', uint8(5), ... % SDS August 2016 which state element the game should treat as depth position
    'xk2DepthVel', uint8(6), ... % SDS August 2016  which state element the game should treat as depth velocity
    'xk2RotatePos', uint8(7), ... % SDS August 2016 which state element the game should treat as rotate velocity
    'xk2RotateVel', uint8(8), ... %SDS August 2016 which state element the game should treat as rotate position
    'autoplayReactionTime', uint16(250), ... % in ms SDS Jan 2016 to be compatible with updateXk
    'autoplayMovementDuration', uint16(1000), ... %in ms  SDS Jan 2016 to be compatible with updateXk
    'exponentialGainBase', single( 1 ), ... % expontial gain base. 1 is special and means unity out/in mapping  SDS Feb 2016
    'exponentialGainUnityCrossing', single(5e-5)... % exponential gain base. At speeds above this (in each dimension), output is > input SDS Feb 2016
);


% task = rig_taskEnumeration.fittsTask;