% %% get the default parameter set
% rig_buildWorkspace;
function taskParamsStruct = movementCueTask_buildWorkspace()
%% model tunable parameters
taskParamsStruct = createTunableStructure('movementCueTask','taskParameters', 'taskParamsBus',...
    'gain',double(ones(1,double(xkConstants.NUM_TARGET_DIMENSIONS)) ),... % SDS August 2016 added third and fourth dimensions
    'mouseOffset',uint16([3400 2950]),... % empirical values from dell laptop trackpad
    'workspaceX',double([-500 500]),...
    'workspaceY',double([-500 500]),...
    'workspaceZ',double([-500 500]),...  Needed for generalized updateXk SDS August 2016
    'workspaceR',double([-3.142 3.142]),...  Needed for generalized updateXk SDS August 2016
    'restDuration',double(2000),...
    'movementDuration',double(2000),...
    'holdDuration',double(2000),...
    'returnDuration',double(2000),...
    'repsPerBlock',double(10),...
    'whichMovements', ones([1 50],'uint8'),...
    'numMovements',uint8(1),...
    'numTrials',uint16(1),...
    'movementOrder',zeros([1 movementConstants.MAX_CUED_MOVEMENTS+0],'uint8'),...
    'delayOrder',zeros([1 movementConstants.MAX_CUED_MOVEMENTS+0],'uint16'),...
    'playSpokenCues',true,...
    'inputType',uint16(cursorConstants.INPUT_TYPE_MOUSE_ABSOLUTE),...
    'gloveBias',uint16(zeros([1 5])),...
    'useGloveLPF', false,...
    'gloveLPNumerator', double(zeros(1, 11)), ...
    'gloveLPDenominator', double(zeros(1, 11)), ...
    'useMouseLPF', false,...
    'mouseLPNumerator', double(zeros(1, 11)), ...
    'mouseLPDenominator', double(zeros(1, 11)), ...
    'stopOnClick',true, ...
    'xk2HorizontalPos', uint8(1), ... % SDS August 2016   which state element the game should treat as horizontal position
    'xk2HorizontalVel', uint8(2), ... % SDS August 2016  which state element the game should treat as horizontal velocity
    'xk2VerticalPos', uint8(3), ... % SDS August 2016 which state element the game should treat as vertical position
    'xk2VerticalVel', uint8(4), ... % SDS August 2016  which state element the game should treat as vertical velocity
    'xk2DepthPos', uint8(5), ... % Not used for this task but updatexk expects it
    'xk2DepthVel', uint8(6), ... % Not used for this task but updatexk expects it
    'xk2RotatePos', uint8(7), ... % Not used for this task but updatexk expects it
    'xk2RotateVel', uint8(8)... % Not used for this task but updatexk expects it
);

% behaviorPacketBus_buildWorkspace;
% clickParameters_buildWorkspace;
% postProcessing_buildWorkspace;
% taskOutput_buildWorkspace;

% %% movementParameters Bus
% movementParams = Simulink.Bus;
% movementParams.Elements(end+1) = createBusElement('restDuration', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('movementDuration', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('holdDuration', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('returnDuration', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('repsPerBlock', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('whichMovements', [1 18], 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('randomSeed', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('expRandMu', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('expRandMin', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('expRandMax', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('expRandBinSize', 1, 'double', 'fixed');
% movementParams.Elements(end+1) = createBusElement('useRandomDelay', 1, 'uint16', 'fixed');


% task = rig_taskEnumeration.movementCue;