function taskParamsStruct = robotTask_buildWorkspace()
% Created 10 February 2017 by SDS. This task will handle our early efforts
% at robotic control. For starters it will be a clone of cursorTask, and
% then I'll prune and extend as needed
taskParamsStruct = createTunableStructure('robotTaskSplit','taskParameters', 'taskParamsBus',...
   'targetDiameter',single(60),... % made single from uint16 Dec 2016 SDS
    'maxTaskTime',uint32(0),...
    'holdTime', int16(500),... % SDS Dec 15 2016, changed from uint16 to int16 to allow negative "bonus" (or panlty) time in tasks
    'trialTimeout',uint16(15000),...
    'numTrials',uint16(100),...
    'randomSeed',double(1),...
    'expRandMu',double(700),...
    'expRandMin',double(500),...
    'expRandMax',double(1000),...
    'expRandBinSize',double(200),...
    'taskType',uint32(cursorConstants.TASK_CENTER_OUT),...
    'targetInds',single(zeros([double(xkConstants.NUM_TARGET_DIMENSIONS), cursorConstants.MAX_TARGETS])),...  % target LOCATIONS (bad name). Uses a fair number of bytes, lower if running out. SDS Dec 2016, changed from int16 to single to accomodate change to cm units
    'numTargets',uint16(0),...
    'gain',double(zeros(1,double(xkConstants.NUM_TARGET_DIMENSIONS)) ),... % SDS August 2016 added third and fourth dimensions
    'failurePenalty',uint16(1000),...
    'cursorDiameter',single(30),... % made single from uint16 Dec 2016 SDS
    'inputType',uint16(cursorConstants.INPUT_TYPE_MOUSE_ABSOLUTE),...
    'gloveBias',uint16(zeros([1 double(xkConstants.NUM_STATE_DIMENSIONS)])),... % SDS July 2016 (was [1 5] before)
    'useRandomDelay',uint16(0),...
    'mouseOffset',uint16([3400 2950]),... % empirical values from dell laptop trackpad
    'workspaceX',double([-500 500]),...
    'workspaceY',double([-500 500]),...
    'workspaceZ',double([0 0]),... % depth boudns. Keep as zero unless this dim being used.
    'workspaceR',double([0 0]),... % rotation bounds. Keep as zero unless this dim being used.
    'showScores',false,...
    'trialsPerScore',uint16(16),...
    'cursorColorClick',single([200 90 50]'),...
    'recenterOnFail',false,...
    'recenterOnSuccess',false,...
    'recenterDelay',uint16(0),...
    'initialInput',uint16(cursorConstants.INPUT_TYPE_DECODE_V),...
    'clickPercentage',double(0),...
    'lockFingerPosition',false,...
    'fingerPositionTolerance',double(10),...
    'failOnLiftoff',false,...
    'errorAssistR',single( zeros(1, double( xkConstants.NUM_TARGET_DIMENSIONS ) ) ), ...      % slows wrong-direction movement (relative to cursor-target axis) in each dimension separately
    'errorAssistTheta',single( zeros(1, double( xkConstants.NUM_TARGET_DIMENSIONS ) ) ), ...  % attenuates orthogonal component of movement (relative to cursor-target axis) in each dimension separately
    'errorAssistAxis',single( zeros(1, double( xkConstants.NUM_TARGET_DIMENSIONS ) ) ), ...   % New October 2016, attentuates wrong-direction movement (relative to cardinal axes) in each dimension 
    'useGloveLPF', false,... 
    'gloveLPNumerator', double(zeros(1, 11)), ...
    'gloveLPDenominator', double(zeros(1, 11)), ...
    'gloveNonlinearCorrection', false,...
    'gloveYCorrection', double(2),...
    'gloveXCorrection', double(1.5),...
    'useMouseLPF', false,...
    'soundOnFail', true,...
    'soundOnGo', false,...
    'soundOnSuccess', true,...
    'soundOnOverTarget', false,...
    'mouseLPNumerator', double(zeros(1, 11)), ... % used in taskBlock, not in this specificTask, but still needed
    'mouseLPDenominator', double(zeros(1, 11)), ... % used in taskBlock, not in this specificTask, but still needed
    'stopOffTarget',true, ...
    'stopOnClick',true, ...
    'outputType', uint16(-1),... % not assigned to an output type, hopefully will be just ignored.  %     'outputType', uint16(cursorConstants.OUTPUT_TYPE_CURSOR),...
    'xk2HorizontalPos', uint8(1), ... % SDS July 2016   which state element the game should treat as horizontal position
    'xk2HorizontalVel', uint8(2), ... % SDS July 2016  which state element the game should treat as horizontal velocity
    'xk2VerticalPos', uint8(3), ... % SDS July 2016 which state element the game should treat as vertical position
    'xk2VerticalVel', uint8(4), ... % SDS July 2016  which state element the game should treat as vertical velocity
    'xk2DepthPos', uint8(5), ... % SDS August 2016 which state element the game should treat as depth position
    'xk2DepthVel', uint8(6), ... % SDS August 2016  which state element the game should treat as depth velocity
    'xk2RotatePos', uint8(7), ... % SDS August 2016 which state element the game should treat as rotate velocity
    'xk2RotateVel', uint8(8),... %SDS August 2016 which state element the game should treat as rotate position
    'gridEdges', single( zeros( uint16(cursorConstants.MAX_TILES_PER_DIM), uint16(xkConstants.NUM_TARGET_DIMENSIONS) ) ), ... %  (N+1) x D array with the boundaries along each dimension for each of the tiles along the d'th gridlike task dimension. SDS December 2016
    'gridTilesEachDim', uint16( zeros( uint16(xkConstants.NUM_TARGET_DIMENSIONS),1 ) ), ... % will be used in task to index into gridEdges
    'newTrialAddedDwell', uint16(0), ... % For Gridlike task, gives this much extra time after a new trial SDS Dec 2016
    'autoplayReactionTime', uint16(250), ... % in ms SDS Dec 2016 
    'autoplayMovementDuration', uint16(1000), ... %in ms  SDS Dec 2016
    'exponentialGainBase', single( 1 ), ... % expontial gain base. 1 is special and means unity out/in mapping  SDS Feb 2016
    'exponentialGainUnityCrossing', single(5e-5),... % exponential gain base. At speeds above this (in each dimension), output is > input SDS Feb 2016
    'targetRotDiameter', single(0.020), ... % Rotatory diamter. Scalar for now while we're in 4D, later this could be expanded if we want different sizes in each rotatory dim SDS Feb 2017
    'autoplayRotationStart', uint16(250), ... % in MS, when (after the start of an autoplay trial) the autoplay rotation begins. % SDS BJ Feb 2017
    'autoplayRotationDuration', uint16(600), ... . Duration of autoplay rotation. In ms. SDS Feb 2017
    'randomTaskTargetDiameters', single(zeros(1, cursorConstants.MAX_DIAMETERS)), ... % For random target task, on each trial the target diameter  is randomly picked from the nonzero elements of this list SDS Mar 2017
    'randomTaskTargetRotDiameters', single(zeros(1, cursorConstants.MAX_DIAMETERS)), ... % For random target task, on each trial the target rotation diameter  is randomly picked from the nonzero elements of this list SDS Mar 2017
    'numDisplayDims', uint8(3), ... % Added to vizPacket, tells display machine what dimensionality visualizations to use. Means we don't need to recompile if going from 4D to 3D SDS Mar2017
    'cursorColorOpen', single([60 255 30]'), ...% in SCL shows grasp open state. Used by robotTask
    'cursorColorClosed', single([255 0 0]') ...% in SCL shows grasp closed state. Used by robotTask
);
