function sentenceText = loadSentenceText()
    sentenceText = {
        'the > quick > brown > fox > jumps > over > the > lazy > dog~',
        'imagine > all > the > people > living > life > in > peace~',
        'ask > not > what > your > country > can > do > for > you~',
        'the > boycott > didn''t > appear > to > have > hurt > their > business > one > bit~',
        'but > that > seemed > to > him > to > be > the > worst > possible > tactic > to > employ~',
        'then > she > kissed > her > fist > and > tossed > the > penny > into > the > reflecting > pond > full > of > pine > needles~',
        'we > tried > everything > else~',
        'music > thumped > from > a > club > two > blocks > away~',
        'what > are > you > doing > calling > on > a > friday > night?',
        'i > brought > this > from > a > bakery > near > me~',
        'have > you > ever > seen > a > large > cat > fold > itself > into > a > tiny > shoe > box?',
        'that''s > a > promise~',
        'thanks > so > much, > honey~',
        'truly, > maggie > was > the > closest > thing > to > a > sister > she > had, > at > least > amongst > relatives~',
        'you > want > me > to > sing?',
        'the > jeep > was > thirsty > so > i > stopped > for > gas > on > the > edge > of > town~',
        'my > parents > went > to > visit > mahlon > and > maggie > and > the > children~',
        'and > i > promise > we''ll > do > our > best > to > treat > the > old > place > with > the > respect > it > deserves~',
        'so > far, > i > haven''t > had > a > lot > of > luck > with > that~',
        'of > course, > i > was > always > aware > of > my > surroundings > when > she > was > with > me~',
        'even > mother > might > roll > her > eyes~',
        'my > family > has > owned > the > place > for > close > to > fifty > years~',
        'dantrelle > nodded > and > i > pulled > out > my > biggest > pot > and > heated > the > oil~',
        'the > treatment > protocol > for > burn > victims > is > almost > as > painful > as > the > injury > itself~',
        'jake > wants > a > normal > life~',
        'it > was > quite > a > sight~',
        'michael > never > goes > anywhere > without > looking > over > his > shoulder~',
        'i > want > to > bring > in > our > legal > team~',
        'he > has > great > hair~',
        'what > lasting > impact > did > that > have > on > you?',
        'so > within > each > company, > the > results > should > be > exactly > the > same~',
        'we''re > not > going > to > live > under > that > threat~',
        'i''m > sorry > it''s > under > these > circumstances~',
        'adopting > a > dog > forced > me > to > get > outside > every > day~',
        'her > grandfather > had > been > arrested~',
        'i > didn''t > want > to > get > out > of > bed~',
        'good > morning, > everyone~',
        'there > are > no > rules > anymore, > luke~',
        'family > is > the > most > important > thing > in > life, > don''t > ever > take > yours > for > granted~',
        'inside > jake''s > duffel > bag, > a > knife > and > a > large > sledgehammer~',
        'so > you > could > literally > see > here''s > what > every > single > person > in > the > company > gets > paid~',
        'basically, > men > were > lying > about > how > much > experience > they > had~',
        'because > less > than > a > quarter > mile > from > where > i''m > standing > right > now > is > where > alla''s > body > was > dumped~',
        'there > are > moments > when > gentle > background > singing > brings > the > song > close > to > gospel~',
        'the > best > way > to > see > a > worthwhile > film > is > however > you > can~',
        'it''s > going > to > be > hard > to > say > goodbye~',
        'one > lesson > i > learned > early > on > happened > when > a > competitor > cut > me > out > of > a > project~',
        'ships > were > the > largest, > most > complex > and > most > expensive > machines > that > existed > at > this > time~',
        'the > super > bowl > is > in > houston, > and > texas > doesn''t > collect > income > tax~',
        'the > answer > is > a > little > bit > of > both~',
        'in > college > football, > salts > are > already > common~',
        'the > boots > are > not > secure > enough > for > fast > movements~',
        'we > can > never > know > for > sure, > jain > notes, > until > we > get > to > such > a > point~',
        'studying > venus > could > offer > a > window > into > our > planet''s > distant > future~',
        'it > fit > easily > into > my > pocket > and > was > a > snap > to > unfold~',
        'maybe > a > few > people > took > comfort > in > this > basically > incomprehensible > word > mess~',
        'facebook > had > dismantled > two > of > the > biggest > barriers > to > people > trying > new > web > services~',
        'who > the > flying > fuck > cleans > their > cat > litter > on > the > kitchen > counter???',
        'this > is > a > historic > opportunity > to > address > one > of > the > biggest > problems > facing > our > electoral > system~',
        'whether > that > happens, > however, > at > the > end > of > the > day > will > depend > on > josh~',
        'so > it > might > be > nice > to > just > kind > of > normalize > it > a > little > bit~',
        'i > told > you > we > were > going > to > bring > this > sucker > home, > and > we > brought > it > home~',
        'reagan > got > his > way > on > the > budget > more > than > 35 > years > ago~',
        'four > years > ago, > i > was > bashful > and > afraid > to > talk > to > anyone~',
        'over > the > weekend, > as > puerto > ricans > ran > perilously > low > on > food, > water > and > fuel, > he > posted > nothing > about > the > crisis~',
        'but > he''s > another > guy > with > a > full > toolbox > of > things > he > can > do~',
        'i > often > saw > diane~',
        'see > you > all > in > cooperstown > this > summer~',
        'long > term, > the > plan > is > to > move > towards > the > classic > american > steakhouse~',
        'it''s > definitely > one > of > the > toughest > times > i''ve > ever > had > to > go > through~',
        'most > prisoners > had > little > hope > of > ever > leaving~',
        'when > the > first > commercial > cameras > appeared > on > the > market, > he > became > obsessed > with > them~',
        'i > think > it > was > well > worth > it~',
        'effort > and > the > way > they > play > is > very > much > an > issue > with > the > giants~',
        'the > coaching > staff > really > cares > about > you~',
        'happy > to > express > my > view > on > that~',
        'she > also > wants > to > spread > the > word > about > eating > the > proper > diet > if > you > have > an > inflammatory > bowel > disease~',
        'he''s > not > going > to > leave > his > wife~',
        'people > forget > that > the > internet > is > a > physical > thing~',
        'a > big > downpour > left > a > puddle > in > the > living > room~',
        'one > man > was > rescued > after > seven > hours > in > the > snow~',
        'while > this > is > not > closure > at > all, > it > closes > a > chapter~',
        'then > i > saw > a > shoe > on > the > ground~',
        'both > young > men > are > angry > over > their > father''s > death~',
        'perhaps > the > court > will > chart > its > owns > course~',
        'schoolchildren > on > the > island > continue > to > read > the > novel~',
        'what > rent > do > you > pay > for > your > housing?',
        'three > studies > had > no > mention > of > ethical > review > or > an > informed > consent > process~',
        'it > is > an > empty > abstraction~',
        'additionally, > the > unique > collaboration > among > many > partners > will > help > to > reduce > duplication > in > our > system~',
        'this > was > captured > by > the > icon > of > a > city > upon > a > hill~',
        'he > watches > from > his > mountain > walls~',
        'this > is > a > question > and > answer > session > between > participants > with > opposing > viewpoints~',
        'future > research > will > take > us > beyond > anecdotes~',
        'plainly, > there > is > a > clear > and > present > need > to > secure > information > in > the > public > and > private > sectors~',
        'i > thought > i > could > fix > it > but > got > trapped > by > my > ego > and > refusal > to > fail~',
        'china > is > one > of > the > nations > that > did > not > sign > the > port > agreement~',
        'this > insight > plays > an > important > role > in > the > economic > analysis > of > criminal > law~',
        'are > there > other > such > rituals?',
        'on > the > other > hand, > let > us > suppose > that > ours > is > the > only > universe~',
        'she > was > a > terrible > woman~',
        'the > agent > on > my > third > trip > was > a > young > woman~',
        'like > many > basaltic > volcanic > peaks, > it > is > a > mecca > for > sea > creatures~',
        'this > marketplace > is > changing > so > fast > that > what > was > news > four > days > ago > is > history > and > is > probably > inaccurate > now~',
        'the > american > business > community > was > slow > to > figure > out > what > worked > in > this > context~'};
end

% tmp = importdata('/Users/frankwillett/Documents/sentences_2.txt');
% for x=1:length(tmp)
%     tmp{x} = strtrim(tmp{x});
%     tmp{x} = strrep(tmp{x},'''','''''');
%     tmp{x} = strrep(tmp{x},'.','~');
%     tmp{x} = strrep(tmp{x},' ',' > ');
%     tmp{x} = lower(tmp{x});
% end
% 
% sentenceCell = fopen('sentenceCell.txt','w');
% for x=1:length(tmp)
%     fprintf(sentenceCell, '''%s'',\n',tmp{x});
% end
% fclose(sentenceCell);
