/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Thu Jul 17 07:44:11 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <windows.h>
#include <winbase.h>
#include        <stddef.h>
#include        <stdlib.h>

#include   "simstruc.h"
#include "xpcimports.h"
#include "time_xpcimport.h"
#include "mex.h"
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void xpctimeinfomulticore_Outputs_wrapper(real_T *xpcTET)
{

    real_T *y;

    y=ssGetOutputPortSignal(S,0);
    switch ((int_T)mxGetPr(FUNCTION_ARG)[0]) {
      case 1:  // TET in seconds
        y[0] = xpceGetTET();
        break;
      case 2:  // time since reboot in ticks
        y[0] = rl32eGetTicksDouble();
        break;
      case 3:  // time since reboot in seconds
        y[0] = xpcGetElapsedTime( (xpcTime *)NULL );
        break;
    }


}
