xpcNICConfig = xpcNICConfigWest();
rigHardware_buildWorkspace
fittsTask_buildWorkspace
decoderSplit_buildWorkspace
postProcessing_buildWorkspace
behaviorPacketBus_buildWorkspace;
taskOutput_buildWorkspace;
clickParameters_buildWorkspace;
