%% need the rigHardware workspace vars
rigHardware_buildWorkspace;

%% bias killer params
biasCorrectionVelocityThreshold = double(0); 
biasCorrectionTau =     double(1000*120);
biasCorrectionEnable =     false;
biasCorrectionInitial =     zeros(2,1);
biasCorrectionType =     uint16(0);
biasCorrectionInitialMeans =     zeros(4,1);
biasCorrectionMeansTau =     double(1000*120);

postProcParamsStruct = createTunableStructure('CLKinSim','postProcParams', 'postProcParams',...
    'biasCorrectionVelocityThreshold',biasCorrectionVelocityThreshold,...
    'biasCorrectionTau',biasCorrectionTau,...
    'biasCorrectionEnable',biasCorrectionEnable,...
    'biasCorrectionInitial',biasCorrectionInitial,...
    'biasCorrectionType',biasCorrectionType,...
    'biasCorrectionInitialMeans',biasCorrectionInitialMeans,...
    'biasCorrectionMeansTau',biasCorrectionMeansTau ...
    );


%% controller params
maxVel = double(0.5);
latency = uint16(100);
maxAccel = double(0.1);
vNoiseStd = double(0.1);
baselineBias = [-0.1; -0.2];

controllerParamsStruct = createTunableStructure('CLKinSim','controllerParams', 'controllerParams',...
    'maxVel',maxVel,...
    'latency',latency,...
    'vNoiseStd',vNoiseStd,...
    'maxAccel',maxAccel,...
    'baselineBias', baselineBias ...
    );
clear maxVel latency vNoiseStd maxAccel baselineBias

%% task params
MAX_TARGETS = 40;
MAX_TRIALS = 200;
taskType = uint16(0);
keyboard = uint16(keyboardConstants.KEYBOARD_GRID_6X6);
screenMidPoint = [960 540];
gridWidth=1000;gridHeight=1000;
keyboardDims = uint16([screenMidPoint - [gridWidth gridHeight]/2 gridWidth gridHeight]);
cursorDiameter = double(30);
targetOrder = zeros([1 MAX_TRIALS],'uint16');
trialTimeout = uint16(15000);
numTrials = uint16(MAX_TRIALS);
runInRealTime = false;
dwellTime = uint16(1000);

taskParamsStruct = createTunableStructure('CLKinSim','taskParams', 'taskParams',...
    'taskType',taskType,...
    'keyboard',keyboard,...
    'keyboardDims',keyboardDims,...
    'cursorDiameter',cursorDiameter,...
    'targetOrder',targetOrder,...
    'trialTimeout',trialTimeout,...
    'numTrials',numTrials,...
    'runInRealTime',runInRealTime,...
    'dwellTime',dwellTime...
    );

clear taskType keyboard keyboardDims cursorDiameter targetOrder trialTimeout numTrials dwellTime runInRealTime



screenMidPoint = [960 540];
gridWidth = 1000; gridHeight = 1000;





k = allKeyboards();

keys1 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard1', 'keysParamsBus',...
    '_1',k(keyboardConstants.KEYBOARD_QWERTY1).keys);
keys2 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard2', 'keysParamsBus',...
    '_2',k(keyboardConstants.KEYBOARD_QWERTY2).keys);
keys3 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard3', 'keysParamsBus',...
    '_3',k(keyboardConstants.KEYBOARD_GRID_6X6).keys);
keys4 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard4', 'keysParamsBus',...
    '_4',k(keyboardConstants.KEYBOARD_GRID_7X7).keys);
keys5 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard5', 'keysParamsBus',...
    '_5',k(keyboardConstants.KEYBOARD_GRID_8X8).keys);
keys6 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard6', 'keysParamsBus',...
    '_6',k(keyboardConstants.KEYBOARD_GRID_9X9).keys);
keys7 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard7', 'keysParamsBus',...
    '_7',k(keyboardConstants.KEYBOARD_GRID_10X10).keys);
keys8 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard8', 'keysParamsBus',...
    '_8',k(keyboardConstants.KEYBOARD_QABCD).keys);
keys9 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard9', 'keysParamsBus',...
    '_9',k(keyboardConstants.KEYBOARD_OPTIII).keys);
keys10 = createTunableStructurePost(...
    'keyboardTask','taskInterface/keyboard10', 'keysParamsBus',...
    '_10',k(keyboardConstants.KEYBOARD_GRID_5X5).keys);
