updateParametersBlock('CLKinSim','postProcParams', 'postProcParams',...
    postProcParamsStruct);


updateParametersBlock('CLKinSim','controllerParams', 'controllerParams',...
    controllerParamsStruct);

updateParametersBlock('CLKinSim','taskParams', 'taskParams',...
    taskParamsStruct);
