%
%
% Counts the number of phonemes segemented in the T5 PTB dataset. General sanity check /
% data inventory.

% Poiunt to where the alignments are. These are generated by Kaldi and packaged by
% package_dir.sh.
alignDir = '/Users/sstavisk/Results/speechContinuous/t5_2018_06_13_PTB/phone_segmentation/praat_alignments';

wavDir = '/Users/sstavisk/Desktop/forGopala/';



%%
fileList = dir( [alignDir filesep '*.txt'] );

% sort by passage number
passageNums = arrayfun( @(x) str2num( strrep( x.name, '.txt', '') ), fileList, 'UniformOutput', true );
[~, newOrder] = sort( passageNums, 'ascend');
fileList = fileList(newOrder);

allPhones = struct(); % will keep a list of all phonemes and how many times they occur
totalPhones = 0;
totalDur = 0;
phonesEachPassage = [];
for iFile = 1 : numel( fileList )
    myFile = [fileList(iFile).folder filesep fileList(iFile).name];

    T = readtable( myFile );
    totalPhones = totalPhones + numel( T.phone );
    phonesEachPassage(iFile) = numel( T.phone );
    for i = 1 : numel( T.phone )
        if isfield( allPhones, T.phone{i})
            allPhones.(T.phone{i}) = allPhones.(T.phone{i}) + 1;
        else
            allPhones.(T.phone{i}) = 1;
        end
    end
    
    % start and end duration
    myDur = T.end_utt(1);
    
    % compare against wav?
    myWavname = sprintf('%spassage_%03i.wav', wavDir, iFile );
    [inWav, Fs] = audioread( myWavname );
    totalDur = totalDur + T.end_utt(1);
    durDiff(iFile) = numel( inWav )/Fs - myDur; % duration differnece between wav and what segmentation says
end

%%
fprintf( '%i unique phones\n', numel( unique( fields( allPhones ) ) ));
fprintf( '%i total phones\n', totalPhones );


