function [topic,props] = Classification        

topic = struct(...
    'name','Classification Properties',...
    'description','Properties related to classification',...
    'id','cl');

props.crossval = struct(...
    'validationFcn',@(x)islogical(x)||(isnumeric(x)&&(x==1||x==0)),...
    'default',false,...
    'attributes',struct('Description','enable cross validation'));

props.cvtype = struct(...
    'validationFcn',@(x)ischar(x)&&any(strcmpi(x,{'kfold','holdout','leaveout','resubstitution'})),...
    'default','kfold',...
    'attributes',struct('Description','cross-validation type ''kfold'',''holdout'',''leaveout'',''resubstition'''));

props.cvbias = struct(...
    'validationFcn',@(x)ischar(x)&&any(strcmpi(x,{'mintest','mintrain','kfold','none'})),...
    'default','mintest',...
    'attributes',struct('Description','modify other parameters to satisfy the requested bias parameter ''mintest'',''mintrain'',''kfold'',''none'''));

props.cvarg = struct(...
    'validationFcn',@isnumeric,...
    'default',10,...
    'attributes',struct('Description','k-fold cross validation'));

props.mintest = struct(...
    'validationFcn',@isnumeric,...
    'default',5,...
    'attributes',struct('Description','minimum number of trials for a test set in cross-validation'));

props.mintrain = struct(...
    'validationFcn',@isnumeric,...
    'default',10,...
    'attributes',struct('Description','minimum number of trials for a training set in cross-validation'));

props.mcreps = struct(...
    'validationFcn',@isnumeric,...
    'default',50,...
    'attributes',struct('Description','number of Monte-Carlo repetitions for validation (see help crossval)'));

props.fittype = struct(...
    'validationFcn',@(x)ischar(x)&&exist(x,'file')==2,...
    'default','fitcdiscr',...
    'attributes',struct('Description','fit type (name of a constructor that returns a fit object)'));

props.fitargs = struct(...
    'validationFcn',@iscell,...
    'default',{{'DiscrimType','diagLinear','Prior','uniform','ScoreTransform','none'}},...
    'attributes',struct('Description','arguments to the fit object constructor'));
