function [topic,props] = Computation        

topic = struct(...
    'name','Computation Properties',...
    'description','Properties related to computation',...
    'id','cp');

props.parallel = struct(...
    'validationFcn',@(x)islogical(x)||(isnumeric(x)&&(x==1||x==0)),...
    'default',true,...
    'attributes',struct('Description','whether to run parfor loops or not'));

props.gpu = struct(...
    'validationFcn',@(x)islogical(x)||(isnumeric(x)&&(x==1||x==0))||islogical(str2num(x)),...
    'default',true,...
    'attributes',struct('Description','whether to use a GPU if one is available'));