function [topic,props] = FiringRate

topic = struct(...
    'name','Spike Firing Rate Properties',...
    'description','Properties related to spike firing rates',...
    'id','fr');

props.min = struct(...
    'validationFcn',@isnumeric,...
    'default',0,...
    'attributes',struct('Description','minimum firing rate threshold'));

props.timeavg = struct(...
    'validationFcn',@(x)islogical(x)||(isnumeric(x)&&(x==1||x==0)),...
    'default',false,...
    'attributes',struct('Description','whether to average features over time (i.e. average value for analysis window)'));

props.forceresolution = struct(...
    'validationFcn',@(x)islogical(x)||(isnumeric(x)&&(x==1||x==0)),...
    'default',false,...
    'attributes',struct('Description','force values to have a minimum resolution (i.e., minimum smallest value)'));

props.featresolution = struct(...
    'validationFcn',@(x)isnumeric(x)&&x>=0,...
    'default',1e-6,...
    'attributes',struct('Description','minimum feature value resolution (i.e., minimum smallest value)'));

props.kernel = struct(...
    'validationFcn',@(x)ischar(x)&&any(strcmpi(x,{'gauss','boxcar','gaussian','triangle'})),...
    'default','gaussian',...
    'attributes',struct('Description','kernel shape to compute firing rate per trial.'));
