% Creates a high pass filter that I'll use for audio smoothing


hpf = designfilt('highpassfir', ...
'PassbandFrequency', 30, 'StopbandFrequency', 10, ...
'PassbandRipple', 0.5, 'StopbandAttenuation', 20, ...
'DesignMethod', 'equiripple', 'SampleRate', 30000 );
