% Takes results with different feature parameters
% generated by WORKUP_classifySpeech.m, and plots them. This is effectively
% a results aggregator / figure making script.
%
% Sergey Stavisky, December 6 2017
clear
% Where are all the files listed below located?
resultsRoot = '/net/derivative/user/sstavisk/Results/speech/classification/';
figuresSaveRoot = [FiguresRootNPTL '/speech/classification/'];





% figureName = 't5.2017.10.25-words feature comparison';
% resultsList = {...
%     't5.2017.10.25-words_237b6b9a16767dbb30f5d2c72c72d897.mat'; % 1 spikes
%     't5.2017.10.25-words_0c0d181cc43f0cfe520acfe9fbaf5c05.mat'; % 2 LMP CAR-removed
%     't5.2017.10.25-words_645eaecc0075f396704f5dda3a0d0e3b.mat'; % 3 65-125
%     't5.2017.10.25-words_adb8cc9ea4acb684885374fcbce86805.mat'; % 4 125-500
%     't5.2017.10.25-words_bab5931eeceb5d15cad159f1b2055577.mat'; % 5 1250 to 5000
%     't5.2017.10.25-words_3c2b018c456d8e971b6d990dbaa283ee.mat'; % 6 spikes + LMP CAR-removed
%     't5.2017.10.25-words_645eaecc0075f396704f5dda3a0d0e3b.mat'; % 7 spikes + 65-125
%     't5.2017.10.25-words_c113685e2894d5c2f15c384c5a82af49.mat'; % 8 spikes + 125-500
%     't5.2017.10.25-words_be47c4fdac15d033d63dcd6db0246673.mat'; % 9 spikes + 125-5000
%     };
% Removed:
% 't5.2017.10.25-words_25bce774de24c603de1d6309ecb6a2c7.mat'; % spikes + LMP
% 't5.2017.10.25-words_4d9cd0533b625f28a0731879036d3083.mat'; % spikes + LMP CAR-remvoved + 125-5000
% 't5.2017.10.25-words_a3330f1d11969ae48ff092c52debfa20.mat'; % 3 65-125 100 ms
%     't5.2017.10.25-words_d706528d7d1827ade94696abde78135b.mat'; % 7 spikes + 65-125 100 ms
%     
    
% figureName = 't5.2017.10.23-phonemes feature comparison';
% resultsList = {...
%     't5.2017.10.23-phonemes_3c098d15c35a6bdf82ca1cd6b8e3b9b4.mat'; % 1 spikes
%     't5.2017.10.23-phonemes_c7db0f45c7f4687a281390e9dee23747.mat'; % 2 LMP CAR-removed
%     't5.2017.10.23-phonemes_6385e38e22f91d1310daa18401ad4617.mat'; % 3 65-125 50ms bin
%     't5.2017.10.23-phonemes_9b781cb09b4a200fccee66200e84d6a6.mat'; % 4 125-250 
%     't5.2017.10.23-phonemes_1d0fd803b57e330807593c7e9f233130.mat'; % 5 125-5000
%     't5.2017.10.23-phonemes_6f651e1dca2cfa6ff84ce1066afff7e0.mat'; % 6 spikes + LMP CAR-removed
%     't5.2017.10.23-phonemes_63c4555b7fe709844c3f35be60124de5.mat'; % 7 spikes + 65-125 50 ms bin
%     't5.2017.10.23-phonemes_672de5caf3c9965bde704307d3b7a813.mat'; % 8 spikes + 125-500
%     't5.2017.10.23-phonemes_a260c17c212e26eefc32dcd86388cfe3.mat'; % 9 spikes + 125-5000
% };
% Removed:
%    't5.2017.10.23-phonemes_175fd17b715247e724eb82f567af9035.mat'; %   65-125 100 ms bin
%  t5.2017.10.23-phonemes_954e624cc7afda039532818978e7a0b5.mat'; %  spikes + LMP % removed because it's worse than without CAR
%  't5.2017.10.23-phonemes_0403a1dca79ee6b07b6c7a0aa4776a97.mat'; % spikes + LMP CAR-removed + 125-5000 % removed from lot, too busy. Can say adding additional (third) didn't help
%     't5.2017.10.23-phonemes_9b781cb09b4a200fccee66200e84d6a6.mat'; % 4 125-500 from LPF (so really 125-250)
%  t5.2017.10.23-phonemes_feb3146497ab23857bdba09f099745d7.mat % spikes + 125-500 from raw
%    't5.2017.10.23-phonemes_a55080da4783bf9c21c43c18dcbffe2e.mat'; % 7 spikes + 65-125 100 ms bin

% 
% figureName = 't8.2017.10.17-phonemes feature comparison';
% resultsList = {...
%     't8.2017.10.17-phonemes_2fd3f086a29e75ca34a043ff049752bf.mat'; % 1 spikes
%     't8.2017.10.17-phonemes_662a7a9e38aa76c55502561ad2b00298.mat'; % 2 LMP CAR-restricted
%     't8.2017.10.17-phonemes_b7b39966d1c9e4e586524e2d9d50cad8.mat'; % 3 65-125
%     't8.2017.10.17-phonemes_ee4b179e232e26ea499a236e20a4820f.mat'; % 4 125-5000.0
%     't8.2017.10.17-phonemes_41d1642c2304ff47c523134234483f8c.mat'; % 5 125 to 5000 no CAR
%     't8.2017.10.17-phonemes_6abbbbbb7cecff6620023b42232944f9.mat'; % 6 spikes + LMP CAR-restricted
%     't8.2017.10.17-phonemes_d573eeeb1bab1583109b9d4fe30b3134.mat'; % 7 spikes + 65-125
%     't8.2017.10.17-phonemes_a3700a54a22b2a511753b992cab54455.mat'; % 8 spikes + 125-500
%     't8.2017.10.17-phonemes_33e029b0074e9aa0cf17944264dbd4da.mat'; % 9 spikes + 125-5000
%     };
% Removed
%     't8.2017.10.17-phonemes_9aec91c8c4df7f5c9f1681bf1b10e797.mat'; % spikes + LMP CAR-restricted + 125-5000
%   't8.2017.10.17-phonemes_05d87b0d7fb04ce247c8d3a5492936f4.mat'; % 7 spikes + 65-125 100 ms bin
%     't8.2017.10.17-phonemes_85e7367b7304e41d9516981f0c18bcf9.mat'; % 3 65-125 100 ms bin
%     't8.2017.10.17-phonemes_d6e13e16fa5f4d41ae2df1f9d0af4fcc.mat'; % 7 spikes + 65-125
% 
% %
figureName = 't8.2017.10.18-words feature comparison';
resultsList = {...
    't8.2017.10.18-words_740ac2cc7e59060bfc404ec53691695f.mat'; % 1 spikes
    't8.2017.10.18-words_4d5b9a1fc1633f6d354141751656bb08.mat'; % 2 LMP CAR-removed
    't8.2017.10.18-words_0858d968dfebe5c2b9cfef9d774b0424.mat'; % 3 65-125
    't8.2017.10.18-words_bb1d3b540a9966e024ac6a0a43c347e4.mat'; % 4 125-500
    't8.2017.10.18-words_7ee214f6540c2a8ef4dc82720b063f21.mat'; % 5 125-5000 No Car
    't8.2017.10.18-words_dabaae2bc7065a5d3fd41d65045589df.mat'; % 6 spikes + LMP CAR-remove
    't8.2017.10.18-words_caeefd125f23ef34c53397b91b5c1b80.mat'; % 7 spikes + 65-125
    't8.2017.10.18-words_21ff8e800bf47c15550d1e3c6b0e9d97.mat'; % 8 spikes + 125-500
    't8.2017.10.18-words_a7dc9c7ce7ebdbf6a2359c34c4a2a599.mat'; % 9 spikes + 125-5000
};

% Removed
%     't8.2017.10.18-words_f50234a40b04724311d2f0fcb2c85244.mat'; % spikes + LMP CAR-remove + 125-5000
%     't8.2017.10.18-words_83bcccac5111e820d251d890ff4e1be7.mat'; % 7 spikes + 65-125 100 ms
%     't8.2017.10.18-words_df496f99a56fb425379f4c9f5c6e3cfc.mat'; % 3 65-125 100 ms
        
colors = jet( numel( resultsList ) );




% figureName = 'No CAR vs CAR T8';
% resultsList = {...
%     't8.2017.10.17-phonemes_d3a95083e0160c75d528d59ee7e52ceb.mat'; % LMP No CAR
%     't8.2017.10.17-phonemes_66247d3b79c1fa682c60e1f8095ef371.mat'; % LMP CAR
%     't8.2017.10.17-phonemes_662a7a9e38aa76c55502561ad2b00298.mat';% LMP CAR-remove
%     't8.2017.10.17-phonemes_41d1642c2304ff47c523134234483f8c.mat'; % 125 to 5000 no CAR
%     't8.2017.10.17-phonemes_85a47bbbefffef5a26640c3068b60a1c.mat'; %125 to 5000 CAR
%     't8.2017.10.17-phonemes_0c4bdd7f9cfa181d153880ca98b3ddbf.mat'; %250 to 5000 No CAR
%     't8.2017.10.17-phonemes_93888f1965a3c3330f965cb3fb56f1ca.mat'; % 250 to 5000 CAR
%     
%     't8.2017.10.18-words_e0c62a0d034a9207aa4fce26c237e6be.mat'; % LMP no CAR
%     't8.2017.10.18-words_37976c8978d118cb4bc9ec1517c95729.mat';  % LMP CAR
%     't8.2017.10.18-words_4d5b9a1fc1633f6d354141751656bb08.mat'; % LMP removed-CAR
%     't8.2017.10.18-words_7ee214f6540c2a8ef4dc82720b063f21.mat'; % 125 to 5000 No Car
%     't8.2017.10.18-words_304072eeae40794c3069ab0360b372e5.mat'; % 125 to 5000 CAR
%     't8.2017.10.18-words_3bf3a57481696d1ec0bb15575ff1ea80.mat'; %250to5000 No CAR
%     't8.2017.10.18-words_91ed960b084526d28ece2083ce75b78d.mat'; %250to5000  CAR
%   
% };
% colors = [...
%     0 0 0.5;
%     .5 0 0;
%     0 .5 0;
%     0 0 .5;
%     .5 0 0;
%     0 0 .5;
%     .5 0 0;
%     
%     0 0 1;
%     1 0 0;
%     0 1 0;
%     0 0 1;
%     1 0 0;
%     0 0 1;
%     1 0 0;
%     ];

%%
% figureName = 'No CAR vs CAR T5';
% resultsList = {...
%    
%     't5.2017.10.23-phonemes_8cbe5ccd6c2d87051115ec13572a66ca.mat'; % :LMP No CAR
%     't5.2017.10.23-phonemes_f309db4c64cb5a3ae4380dc881390724.mat'; % LMP CAR
%     't5.2017.10.23-phonemes_c7db0f45c7f4687a281390e9dee23747.mat'; % LMP removed-CAR
%     't5.2017.10.23-phonemes_1d0fd803b57e330807593c7e9f233130.mat'; % 125 to 5000 no CAR
%     't5.2017.10.23-phonemes_8b255c973209461d5c3d7771c3a69960.mat';  % 125 to 5000  CAR
%     't5.2017.10.23-phonemes_29aff6d2e07626ac4729a99b6df61807.mat'; % 250 to 5000 no CAR
%     't5.2017.10.23-phonemes_b249325f0854adf4fc84aed09ee89019.mat'; % 250 to 5000  CAR
%     't5.2017.10.23-phonemes_631ceff59dc50b9dcd3f7a49bc72da30.mat';% 250 to 5000 CAR-removed
%     
%     't5.2017.10.25-words_2dd3273ce20e57bd28aa069bf3e813b0.mat'; % LMP No CAR
%     't5.2017.10.25-words_cee6a0515bd7de29d52a299d4c0427be.mat'; % LMP CAR
%     't5.2017.10.25-words_0c0d181cc43f0cfe520acfe9fbaf5c05.mat'; % LMP removed-CAR
%     't5.2017.10.25-words_bab5931eeceb5d15cad159f1b2055577.mat'; %  %125 to 5000 No CAR
%     't5.2017.10.25-words_179bfd9d3240fd512eb8b0495f338cc8.mat'; %125 to 5000 CAR
%     't5.2017.10.25-words_4402fe1084313930ed4cacabe410f749.mat'; % 125 to 5000 removed-CAR
%     't5.2017.10.25-words_7d6325b82844d7c475aa4ba1aa74930b.mat' % 250 to 5000 No CAR
%     't5.2017.10.25-words_962e2d29f83bfb08b6c30f37dcbe0683.mat';% 250 to 5000 CAR
% };
% colors = [...  
%     0 0 .5;
%     .5 0 0;
%     0 .5 0;
%     0 0 .5;
%     .5 0 0;
%     0 0 .5;
%     .5 0 0;
%     0 .5 0;
%      
%     0 0 1;
%     1 0 0;
%     0 1 0; 
%     0 0 1;
%     1 0 0;
%     0 1 0;
%     0 0 1;
%     1 0 0;
%     ];

%%
% figureName = 'With or Without Exclude Channels';
% resultsList = {...
%     't5.2017.10.23-phonemes_a260c17c212e26eefc32dcd86388cfe3.mat'; % spikes + 125-5000, yes exclude
%     't5.2017.10.23-phonemes_e7992b5695a917b9ff70d33e4322822f.mat'; % spikes + 125-5000, NO EXCLUDE
%     't5.2017.10.25-words_be47c4fdac15d033d63dcd6db0246673.mat'; % spikes + 125-5000, yes exclude
%     't5.2017.10.25-words_312908c4889c58088833ec4ddc7a6a39.mat'; % SPIKES + 125-5000, NO EXCLUDE
%     
%     't8.2017.10.17-phonemes_33e029b0074e9aa0cf17944264dbd4da.mat'; % spikes + 125-5000, yes exclude
%     't8.2017.10.17-phonemes_52025180d7f3ae0b12d3999ad0384785.mat'; % spikes + 125-5000, NO EXCLUDE
%     't8.2017.10.18-words_a7dc9c7ce7ebdbf6a2359c34c4a2a599.mat'; % spikes + 125-5000, yes exclude
%     't8.2017.10.18-words_107bf947b55c522b51abd1d7da47c196.mat'; % spikes + 125-5000, NO EXCLUDE
% };
% colors = [...  
%     0 0 .5;
%     .5 0 0;
%     0 0 .5;
%     .5 0 0;
% 
%     0 0 1;
%     1 0 0;
%     0 0 1;
%     1 0 0;
%     ];

%% Load all the results

for i = 1 : numel( resultsList )
    in = load( [resultsRoot resultsList{i}] );
    results{i} = in.classifyResult;
    params{i} = in.params;
    
    % What were the neural feature(s)?
    if isfield( params{i}, 'componentNeuralFeatures' )
        conditionNames{i} = CellsWithStringsToOneString( params{i}.componentNeuralFeatures );
    else
        conditionNames{i} = params{i}.neuralFeature;
    end
    
    % What were the different folds' classification accuracies?
    dat(:,i) = results{i}.classificationSuccessRate;
end


%%

[stats, figh, axh] = MultipointComparisonBarplots( dat, 'conditionNames', conditionNames, ...
    'sigTestToCond1', true, 'pairedTtest', false, 'showPairLines', false, 'bridges', [], ...
    'showSigTest', true, 'SEM', true, 'YLim', [0 1], 'numericMean', true, 'colors', colors);
MakeTitle( figureName );
figh = ConvertToWhiteBackground( figh );
titlestr = figureName;
figh.Name = titlestr;
ExportFig( figh, [figuresSaveRoot titlestr] );
