%
% Comparison files generated by WORKUP_speechCIS_regularized.m and
% WORKUP_compare_jPCs_CIS.m
%
% Sergey Stavisky, August 14 2019
clear
% One pair per dataset. CIS first, then jPC
filePairs = {...
    {'/Users/sstavisk/Results/speech/dPCA/regularized/dPCs-t5.2017.10.25-words.mat' , '/Users/sstavisk/Results/speech/jPCA/jPCs-t5.2017.10.25-words.mat'}, ...
    {'/Users/sstavisk/Results/speech/dPCA/regularized/dPCs-t5.2017.10.23-phonemes.mat' , '/Users/sstavisk/Results/speech/jPCA/jPCs-t5.2017.10.23-phonemes.mat'}, ...
    {'/Users/sstavisk/Results/speech/dPCA/regularized/dPCs-t5.2018.12.12-words_noRaw.mat' , '/Users/sstavisk/Results/speech/jPCA/jPCs-t5.2018.12.12-words_noRaw.mat'}, ...
    {'/Users/sstavisk/Results/speech/dPCA/regularized/dPCs-t5.2018.12.17-words_noRaw.mat' , '/Users/sstavisk/Results/speech/jPCA/jPCs-t5.2018.12.17-words_noRaw.mat'}, ...
    {'/Users/sstavisk/Results/speech/dPCA/regularized/later/dPCs-t8.2017.10.18-words-8dim.mat' , '/Users/sstavisk/Results/speech/jPCA/jPCs-t8.2017.10.18-words.mat'}, ...
    {'/Users/sstavisk/Results/speech/dPCA/regularized/later/dPCs-t8.2017.10.17-phonemes-8dim.mat' , '/Users/sstavisk/Results/speech/jPCA/jPCs-t8.2017.10.17-phonemes.mat'}, ...
    };


figh = figure;
figh.Color = 'w';

Ndatasets = numel( filePairs );
for iDataset = 1 : Ndatasets
    fprintf(' loading %s\n', filePairs{iDataset}{1} );
    inDPC = load( filePairs{iDataset}{1} );
    CIS1 = inDPC.Vreordered(:,1);
    
    fprintf(' loading %s\n', filePairs{iDataset}{2} );
    inJPC = load( filePairs{iDataset}{2} );
    JPC1 = inJPC.Summary.jPCs_highD(:,1);
    JPC2 = inJPC.Summary.jPCs_highD(:,2);

    figure;
    plot( CIS1, 'r')
    hold on;
    plot( JPC1, 'g')
    plot( JPC2, 'b')
    myDataset = pathToLastFilesep( filePairs{iDataset}{1}, 1 );
    title( myDataset )
    
    numJPCs = size( inJPC.Summary.jPCs_highD, 2 );
    
    suba = rad2deg( subspacea( CIS1, [JPC1, JPC2] ) );
    fprintf('\n-----------\n%s\n----------\n', myDataset);
    fprintf('Subspace angle between CIS1 and first 2 jPC dims is %.2f deg\n', ...
        suba );

    
    % How orthogonal is CIS_1 to the jPC dims? 
    for i = 1 : numJPCs
        myJPC = inJPC.Summary.jPCs_highD(:,i);
        angleBetween = angleBetweenVectors(CIS1,myJPC);
        if angleBetween > 90
            angleBetween = 180- angleBetween;
        end
        % statistical test for substantial snon-orthogonality
        % taken from Kobak et al 2016 code (plot_dpca.m)
        [~, psp] = corr( CIS1, myJPC, 'type', 'Kendall');

        fprintf('  Angle between CIS1 and JPC%i is %.3fdeg, %f p-value that this is significantly non-orthogonal', ...
            i,  angleBetween, psp)
        if psp < 0.001
            fprintf(' **\n')
        elseif psp < 0.01
            fprintf(' *\n')
        else
            fprintf('\n')
        end
     
    end

    % plot the stick-and-rod
    figure( figh )
    axh(iDataset) = subplot( 1, Ndatasets, iDataset );
    circle( [0,0],1,[.5 .5 .5],1)
    ch = axh(iDataset).Children;
    ch.Color = 'b';
    box off
    axh(iDataset).XAxis.Visible = 'off';
    axh(iDataset).YAxis.Visible = 'off';
    axh(iDataset).ZAxis.Visible = 'off';
    
    axis equal
    rayx = cos( deg2rad( suba ) );
    rayy = sin( deg2rad( suba ) );
    lh = line( [0 0], [0 rayx], [0 rayy], 'LineWidth', 2', 'Color', 'r');
    view(3);
    title( myDataset );
    
    
end