function layout(this)

outer_left_margin = 50;
outer_bottom_margin = 50;
outer_top_margin = 50;
outer_right_margin = 50;

panel_left_margin = 30;
panel_right_margin = 50;

col1_width = 570;
col2_width = 470;
col_spacing = 50;

gridinfo_textlbl_width = 150;
gridinfo_editfld_width = 240;
gridinfo_height = 30;
gridinfo_field_vertical_spacing = 14;

button_spc = 20;
text_edit_spc = 20;
fig_width = 1200;
fig_height = 800;

base_font_sz = 12;
title_font_sz = 16;

summary_textlbl_width = 200;
summary_textval_width = 200;
summary_field_height = 25;
summary_field_vertical_spacing = 8;
summary_field_height_small = 17;
summary_field_vertical_spacing_small = 4;

% create the figure
set(0,'units','pixels');
screen_size = get(0,'ScreenSize');
fig_left = (screen_size(3)-screen_size(1))/2 - fig_width/2;
fig_bottom = (screen_size(4)-screen_size(2))/2 - fig_height/2;
figpos = [fig_left fig_bottom fig_width fig_height];
this.hFigure = figure(...
    'Position',figpos,...
    'PaperPositionMode','auto',...
    'NumberTitle','off',...
    'WindowKeyPressFcn',@(h,kp)keyPressHandler(kp),...
    'MenuBar','none','ToolBar','none');
this.hFigure.CloseRequestFcn = @(src,dt)close(this);




%-------------------------------------------------------------------------%
%  MAPFILE EDIT/LOAD/SAVE
%-------------------------------------------------------------------------%

% create mapfile select file, edit box, save/load buttons
currLeft = outer_left_margin;
currBottom = 715;
localWidth = 100;
localHeight = 40;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','on',...
    'String','Select',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',title_font_sz,...
    'Tag','buttonSelectMapfile',...
    'TooltipString','Select a mapfile',...
    'Callback',@(h,evt)buttonSelectMapfile_Callback);

currLeft = currLeft + localWidth + button_spc;
localWidth = 720;
localHeight = 36;
uicontrol(...
    'Parent',this.hFigure,...
    'enable','off',...
    'FontSize',16,...
    'HorizontalAlignment','left',...
    'Position',[currLeft currBottom+2 localWidth localHeight],...
    'String','[No Grids Defined]',...
    'Style','edit',...
    'Tag','editMapfile');

localHeight = 40;
currLeft = currLeft + localWidth + button_spc;
localWidth = 100;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Load',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',title_font_sz,...
    'Tag','buttonLoadMapfile',...
    'TooltipString','Load a grid map',...
    'Callback',@(h,evt)buttonLoadMapfile_Callback);

currLeft = currLeft + localWidth + button_spc;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Save',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',title_font_sz,...
    'Tag','buttonSaveMapfile',...
    'TooltipString','Save the grid map',...
    'Callback',@(h,evt)buttonSaveMapfile_Callback);






%-------------------------------------------------------------------------%
%  GRIDINFO LISTBOX
%-------------------------------------------------------------------------%

% create grid info listbox
currLeft = outer_left_margin;
localHeight = 320;
currBottom = 370;
localWidth = col1_width;
uicontrol(...
    'Parent',this.hFigure,...
    'enable','on',...
    'Position',[currLeft currBottom localWidth localHeight],...
    'String','',...
    'FontName','FixedWidth',...
    'FontSize',base_font_sz,...
    'FontWeight','bold',...
    'Style','listbox',...
    'Tag','listboxGridInfo',...
    'Callback',@(h,evt)listboxGridInfo_Callback);

% create new/edit/delete buttons
localHeight = 30;
currLeft = outer_left_margin;
currBottom = currBottom - localHeight - 15;
localWidth = (col1_width - (65+button_spc) - 2*button_spc)/3;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','on',...
    'String','New',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonNewGrid',...
    'TooltipString','Add a new grid',...
    'Callback',@(h,evt)buttonNewGrid_Callback);

currLeft = currLeft + localWidth + button_spc;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Edit',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonEditGrid',...
    'TooltipString','Edit a grid',...
    'Callback',@(h,evt)buttonEditGrid_Callback);

currLeft = currLeft + localWidth + button_spc;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Delete',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonDeleteGrid',...
    'TooltipString','Delete a grid',...
    'Callback',@(h,evt)buttonDeleteGrid_Callback);


currLeft = currLeft + localWidth + button_spc;
localWidth = 30;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','^',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonMoveGridUp',...
    'TooltipString','Move grid up',...
    'Callback',@(h,evt)buttonMoveGridUp_Callback);
currLeft = currLeft + localWidth + 5;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','v',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonMoveGridDown',...
    'TooltipString','Move grid down',...
    'Callback',@(h,evt)buttonMoveGridDown_Callback);



%-------------------------------------------------------------------------%
%  CHANNEL INFO LISTBOX
%-------------------------------------------------------------------------%



% create all grids / selected grids buttons
currLeft = outer_left_margin;
currBottom = outer_bottom_margin;
localHeight = 30;
localWidth = (col1_width - button_spc)/2;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','All Grids',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonAllGrids',...
    'TooltipString','Display channels from all grids',...
    'Callback',@(h,evt)buttonAllGrids_Callback);

currLeft = currLeft + localWidth + button_spc;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Selected Grid',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonSelectedGrid',...
    'TooltipString','Display channels from selected grid',...
    'Callback',@(h,evt)buttonSelectedGrid_Callback);

% channel display listbox
currLeft = outer_left_margin;
currBottom = outer_bottom_margin + localHeight + 15;
localHeight = 180;
localWidth = col1_width;
uicontrol(...
    'Parent',this.hFigure,...
    'Enable','on',...
    'Position',[currLeft currBottom localWidth localHeight],...
    'String','',...
    'FontName','FixedWidth',...
    'FontSize',base_font_sz,...
    'FontWeight','bold',...
    'Style','listbox',...
    'Tag','listboxChannelInfo',...
    'Callback',@(h,evt)listboxChannelInfo_Callback);







%-------------------------------------------------------------------------%
%  GRID EDIT FIELDS
%-------------------------------------------------------------------------%

% editing fields
currLeft = outer_left_margin + col1_width + col_spacing;
currBottom = 300;
localWidth = col2_width;
localHeight = 400;
hEditPanel = uipanel(...
    'Title','Grid Fields',...
    'FontSize',12,...
    'Parent',this.hFigure,...
    'Units','pixels',...
    'Position',[currLeft currBottom localWidth localHeight]);




% template label/editbox
currLeft = panel_left_margin;
currBottom = 335;
localWidth = gridinfo_textlbl_width;
localHeight = 30;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Template',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textTemplate');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = gridinfo_editfld_width;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom+4 localWidth localHeight],...
    'String',{'No Templates Available'},...
    'Enable','off',...
    'FontSize',base_font_sz,...
    'Style','popupmenu',...
    'Tag','popupTemplate',...
    'Callback',@(h,evt)popupTemplate_Callback);

% location label/editbox
currLeft = panel_left_margin;
currBottom = currBottom - gridinfo_height - gridinfo_field_vertical_spacing;
localWidth = gridinfo_textlbl_width;
localHeight = gridinfo_height;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Brain Area',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textBrainAreas');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = gridinfo_editfld_width;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom+4 localWidth localHeight],...
    'String',{'No Brain Areas Available'},...
    'Enable','off',...
    'FontSize',base_font_sz,...
    'Style','popupmenu',...
    'Tag','popupLocation',...
    'Callback',@(h,evt)popupLocation_Callback);

% hemisphere label/editbox
currLeft = panel_left_margin;
currBottom = currBottom - gridinfo_height - gridinfo_field_vertical_spacing;
localWidth = gridinfo_textlbl_width;
localHeight = gridinfo_height;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Hemisphere',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textHemisphere');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = gridinfo_editfld_width;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom+4 localWidth localHeight],...
    'String',{'Left','Right','None'},...
    'Enable','off',...
    'FontSize',base_font_sz,...
    'Style','popupmenu',...
    'Tag','popupHemisphere',...
    'Callback',@(h,evt)popupHemisphere_Callback);

% grid label label/editbox
currLeft = panel_left_margin;
currBottom = currBottom - gridinfo_height - gridinfo_field_vertical_spacing;
localWidth = gridinfo_textlbl_width;
localHeight = gridinfo_height;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Label',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',12,...
    'Tag','textLabel');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = gridinfo_editfld_width;
uicontrol(...
    'Parent',hEditPanel,...
    'enable','off',...
    'FontSize',base_font_sz,...
    'HorizontalAlignment','left',...
    'Position',[currLeft currBottom+4 localWidth localHeight],...
    'String','[No Grids Defined]',...
    'Style','edit',...
    'Tag','editLabel');

% grid label label/editbox
currLeft = panel_left_margin;
currBottom = currBottom - gridinfo_height - gridinfo_field_vertical_spacing;
localWidth = gridinfo_textlbl_width;
localHeight = gridinfo_height;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Grid Electrodes',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textElectrode');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = gridinfo_editfld_width;
uicontrol(...
    'Parent',hEditPanel,...
    'enable','off',...
    'FontSize',base_font_sz,...
    'HorizontalAlignment','left',...
    'Position',[currLeft currBottom+4 localWidth localHeight],...
    'String','[No Grids Defined]',...
    'Style','edit',...
    'Tag','editElectrode');

% central channels label label/editbox
currLeft = panel_left_margin;
currBottom = currBottom - gridinfo_height - gridinfo_field_vertical_spacing;
localWidth = gridinfo_textlbl_width;
localHeight = gridinfo_height;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','First Amp. Chan.',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textFirstAmpChannel');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = 45;
uicontrol(...
    'Parent',hEditPanel,...
    'enable','off',...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'Position',[currLeft currBottom+4 localWidth localHeight],...
    'String','[No Grids Defined]',...
    'Style','edit',...
    'Tag','editFirstAmpChannel');

currLeft = currLeft + localWidth + 2*text_edit_spc;
localWidthBase = gridinfo_editfld_width - localWidth - 2*text_edit_spc;
localWidth = 0.1*localWidthBase;
uicontrol(...
    'Parent',hEditPanel,...
    'enable','off',...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'Position',[currLeft currBottom+4 localWidth localHeight],...
    'Value',0,...
    'Style','checkbox',...
    'Tag','checkboxBankAlign',...
    'Callback',@(h,evt)checkboxBankAlign_Callback);
currLeft = currLeft + localWidth + 0.2*text_edit_spc;
localWidth = 0.3*localWidthBase;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom 4*localWidth localHeight],...
    'Enable','off',...
    'String','Align',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textAlign');
currLeft = currLeft + localWidth + 0.2*text_edit_spc;
localWidth = 0.1*localWidthBase;
uicontrol(...
    'Parent',hEditPanel,...
    'enable','off',...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'Position',[currLeft currBottom+4 localWidth localHeight],...
    'Value',0,...
    'Style','checkbox',...
    'Tag','checkboxBankLock',...
    'Callback',@(h,evt)checkboxBankAlign_Callback);
currLeft = currLeft + localWidth + 0.1*text_edit_spc;
localWidth = 0.2*localWidthBase;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom 6*localWidth localHeight],...
    'Enable','off',...
    'String','Lock',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textLock');

% create save/reset/cancel buttons
currLeft = panel_left_margin;
currBottom = currBottom - gridinfo_height - gridinfo_field_vertical_spacing;
localWidth = (col2_width - 2*panel_left_margin - 2*button_spc)/3;
localHeight = gridinfo_height;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Save',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonSaveGrid',...
    'TooltipString','Save this grid',...
    'Callback',@(h,evt)buttonSaveGrid_Callback);

currLeft = currLeft + localWidth + button_spc;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Reset',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonResetGrid',...
    'TooltipString','Reset this grid',...
    'Callback',@(h,evt)buttonResetGrid_Callback);

currLeft = currLeft + localWidth + button_spc;
uicontrol(...
    'Parent',hEditPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Cancel',...
    'HorizontalAlignment','left',...
    'Style','pushbutton',...
    'FontSize',base_font_sz,...
    'Tag','buttonCancelGrid',...
    'TooltipString','Cancel this grid',...
    'Callback',@(h,evt)buttonCancelGrid_Callback);






%-------------------------------------------------------------------------%
%  GRID INFO SUMMARY PANEL
%-------------------------------------------------------------------------%

% grid info summary panel
currLeft = outer_left_margin + col1_width + col_spacing;
currBottom = outer_bottom_margin;
localWidth = col2_width;
localHeight = 235;
hSummaryPanel = uipanel(...
    'Title','Summary',...
    'FontSize',12,...
    'Parent',this.hFigure,...
    'Units','pixels',...
    'Position',[currLeft currBottom localWidth localHeight]);

currLeft = panel_left_margin;
currBottom = 170;
localWidth = summary_textlbl_width;
localHeight = summary_field_height;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Number of Grids:',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textNumGridsLabel');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = summary_textval_width;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','[No Grids Defined]',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textNumGridsValue');


currLeft = panel_left_margin + 20;
localHeight = summary_field_height_small;
currBottom = currBottom - localHeight - summary_field_vertical_spacing_small;
localWidth = col2_width - panel_left_margin - panel_right_margin;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','[No Labels]',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',10,...
    'Tag','textGridLabels');


currLeft = panel_left_margin;
localHeight = summary_field_height;
currBottom = currBottom - localHeight - summary_field_vertical_spacing;
localWidth = summary_textlbl_width;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Number of Channels:',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textNumChannelsLabel');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = summary_textval_width;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','[No Grids Defined]',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textNumChannelsValue');


currLeft = panel_left_margin;
currBottom = currBottom - summary_field_height - summary_field_vertical_spacing;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Max Central Channel:',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textMaxCentralChannelLabel');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = summary_textval_width;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','[No Grids Defined]',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textMaxCentralChannelValue');


currLeft = panel_left_margin;
currBottom = currBottom - summary_field_height - summary_field_vertical_spacing;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Central Channels Skipped:',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textCentralChannelsSkippedLabel');
currLeft = currLeft + localWidth + text_edit_spc;
localWidth = summary_textval_width;
uicontrol(...
    'Parent',hSummaryPanel,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','[No Grids Defined]',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',base_font_sz,...
    'Tag','textCentralChannelsSkippedValue');






%-------------------------------------------------------------------------%
%  STATUS BAR
%-------------------------------------------------------------------------%
currLeft = 10;
currBottom = 4;
localWidth = fig_width - 2*currLeft;
localHeight = 20;
uicontrol(...
    'Parent',this.hFigure,...
    'Position',[currLeft currBottom localWidth localHeight],...
    'Enable','off',...
    'String','Ready',...
    'HorizontalAlignment','left',...
    'Style','text',...
    'FontSize',11,...
    'ForegroundColor',[0.7 0.7 0.7],...
    'Tag','textStatus');


this.guiHandles = guihandles(this.hFigure);



%-------------------------------------------------------------------------%
%  CALLBACK FUNCTIONS
%-------------------------------------------------------------------------%

    function keyPressHandler(kp)
    end  % END function keyPressHandler

    function buttonSelectMapfile_Callback
        gui__selectMapfile(this);
    end % END function buttonSelectMapfile_Callback

    function buttonLoadMapfile_Callback
        gui__loadMapfile(this);
    end % END function buttonLoadMapfile_Callback

    function buttonSaveMapfile_Callback
        gui__saveMapfile(this);
    end % END function buttonSaveMapfile_Callback

    function listboxGridInfo_Callback
        selectedRow = gui__getSelectedGrid(this);
        if isnan(selectedRow),return;end
        refreshContent(this);
    end % END function listboxGridInfo_Callback

    function buttonNewGrid_Callback
        this.GuiMode = 'new';
        gui__newGrid(this);
    end % END function buttonNewGrid_Callback

    function buttonEditGrid_Callback
        this.GuiMode = 'edit';
        selectedRow = gui__getSelectedGrid(this);
        if isnan(selectedRow),return;end
        gui__editGrid(this,selectedRow);
    end % END function buttonEditGrid_Callback

    function buttonDeleteGrid_Callback
        selectedRow = gui__getSelectedGrid(this);
        if isnan(selectedRow),return;end
        gui__deleteGrid(this,selectedRow);
    end % END function buttonDeleteGrid_Callback

    function buttonMoveGridUp_Callback
        
        % upward movement is decrementing grid id
        gui__moveGrid(this,-1);
    end % END function buttonMoveGridUp_Callback

    function buttonMoveGridDown_Callback
        
        % downward movement is incrementing grid id
        gui__moveGrid(this,1);
    end % END function buttonMoveGridDown_Callback

    function listboxChannelInfo_Callback
    end % END function listboxChannelInfo_Callback

    function buttonAllGrids_Callback
        this.ChannelDisplayMode = 'allgrids';
        refreshContent(this);
    end % END function buttonAllGrids_Callback

    function buttonSelectedGrid_Callback
        this.ChannelDisplayMode = 'selectedgrid';
        refreshContent(this);
    end % END function buttonSelectedGrid

    function popupTemplate_Callback
        
        % read selected template
        str = get(this.guiHandles.popupTemplate,'String');
        idx = get(this.guiHandles.popupTemplate,'Value');
        if strcmpi(str{idx},'none')
            return;
        end
        template = GridMap.Template(str{idx});
        [~,chaninfo] = template.read;
        
        % get selected grid and identify starting electrode/channel
        if ~isempty(this.hGridMap) && this.hGridMap.NumGrids>0
            if strcmpi(this.GuiMode,'edit')
                [~,selectedGrid] = gui__getSelectedGrid(this);
                first_electrode = this.hGridMap.GridInfo.GridElectrode{selectedGrid}(1);
                first_amp_channel = min(this.hGridMap.ChannelInfo.AmplifierChannel(this.hGridMap.ChannelInfo.GridID==selectedGrid));
            elseif strcmpi(this.GuiMode,'new')
                first_electrode = 1;
                first_amp_channel = max(this.hGridMap.ChannelInfo.AmplifierChannel) + 1;
            end
        else
            first_electrode = 1;
            first_amp_channel = 1;
        end
        
        % update electrode/channel fields
        set(this.guiHandles.editElectrode,'String',util.vec2str(first_electrode - 1 + (1:height(chaninfo))));
        set(this.guiHandles.editFirstAmpChannel,'String',first_amp_channel);
    end % END function popupTemplate_Callback

    function popupLocation_Callback
    end % END popupLocation_Callback

    function popupHemisphere_Callback
    end % END popupHemisphere_Callback

    function checkboxBankAlign_Callback
        curr_checkbox_val = get(this.guiHandles.checkboxBankAlign,'Value');
        
        if isempty(this.hGridMap) || (~isempty(this.hGridMap) && this.hGridMap.NumGrids==0)
            first_chan = 1;
        else
            first_chan = max(this.hGridMap.ChannelInfo.AmplifierChannel) + 1;
        end
        
        if curr_checkbox_val
            currBank = find(cellfun(@(x)ismember(first_chan,x),this.hGridMap.BankInfo.Channel));
            assert(~isempty(currBank),'Could not identify current bank');
            if currBank~=length(this.hGridMap.BankInfo.Channel)
                dx = cellfun(@(x)min(x(1)-first_chan),this.hGridMap.BankInfo.Channel((currBank+1):end));
                whichBank = find(dx>=0,1,'first');
                assert(~isempty(whichBank),'Could not identify bank to align');
                whichBank = currBank + whichBank;
                if currBank~=whichBank
                    first_chan = this.hGridMap.BankInfo.Channel{whichBank}(1);
                end
            end
        else
            if strcmpi(this.GuiMode,'edit')
                [~,~,selectedGridID] = gui__getSelectedGrid(this);
                prevGridID = selectedGridID - 1;
                if prevGridID>=0
                    first_chan = max(this.hGridMap.ChannelInfo.AmplifierChannel(this.hGridMap.ChannelInfo.GridID==prevGridID)) + 1;
                else
                    first_chan = 1;
                end
            elseif strcmpi(this.GuiMode,'new')
                if isempty(this.hGridMap) || (~isempty(this.hGridMap) && this.hGridMap.NumGrids==0)
                    first_chan = 1;
                else
                    first_chan = max(this.hGridMap.Channelinfo.AmplifierChannel) + 1;
                end
            else
                error('Unknown GUI mode "%s"',this.GuiMode);
            end
        end
        set(this.guiHandles.editFirstAmpChannel,'String',sprintf('%d',first_chan));
    end % END checkboxBankAlign_Callback

    function buttonSaveGrid_Callback
        gui__saveGrid(this);
    end % END function buttonSaveGrid_Callback

    function buttonResetGrid_Callback
        gui__resetGrid(this);
    end % END function buttonResetGrid_Callback

    function buttonCancelGrid_Callback
        this.GuiMode = 'view';
        gui__cancelGrid(this);
    end % END function buttonCancelGrid_Callback
end % END function layout