/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Mar 15 07:33:12 2013
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void Cbbg_Test_Samples_Outputs_wrapper(const uint32_T *samplesPerStep,
                          int16_T *sampleData,
                          int32_T *numSamples)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/*
 * Outputs samples in test data format for Cbbg.
 * data cycles through ch, 0, -ch, ch, 0, -ch, ...
 * this is the pattern that test data sink (like cbbg_app) expect to find
 *
 * N. Schmansky, March 2012
 */

#include "cbhwlib_lite.h"

static int g_expectedSign=0;

int samplesToSend,i,ch,idx;

// number of samples we need to output
// note that this number if of course step size dependent per 30Khz,
// ie, step size of 0.0005 is 15 samples
// AND !!!  the size of sampleData is 96 times samplesPerStep, 
// so be sure to check that in Data Properties
samplesToSend = samplesPerStep[0];

// sanity-check
if ((samplesToSend < 0) || (samplesToSend > 30000))
{
    samplesToSend = 0;
}

for (i=0; i < samplesToSend; i++)
{
    // fill one 'sample group' (continuous data) packet of 30K data
    for (ch=1; ch <= NUM_SIM_CHANNELS; ch++)
    {
        idx = (ch-1) + (i*NUM_SIM_CHANNELS);
        sampleData[idx] = ch * g_expectedSign;
    }
    
    // data cycles through ch, 0, -ch, ch, 0, -ch, ...
    // this is the pattern that test data sink (like cbbg_app) expect to find
    if (g_expectedSign == 1)
    {
        g_expectedSign = 0;
    }
    else if (g_expectedSign == 0)
    {
        g_expectedSign = -1;
    }
    else 
    {
        g_expectedSign = 1;
    }
}

numSamples[0] = samplesToSend;
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
