/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Mar 15 07:32:36 2013
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void ProtocolMonitorSim_Outputs_wrapper(const uint32_T *clk,
                          const uint32_T *pktsSent,
                          uint8_T *pktData,
                          real_T *pktSize)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/*
 * This code outputs a Cerebus 'protocol monitor' packet every second.
 *
 * N. Schmansky, March 2012
 */

#include <cbhwlib_lite.h>

static unsigned int lastPktSentClk=0;
static unsigned int lastPktSentCount=0;

// assume no packet will be sent
pktSize[0] = 0;

if (clk[0] >= (lastPktSentClk + TICKS_1S))
{
    // 1s has elapsed since last protocol monitor packet sent, 
    // so send another one...
    cbPKT_SYSPROTOCOLMONITOR* protomonPkt = (cbPKT_SYSPROTOCOLMONITOR*)pktData;
    protomonPkt->time = clk[0];
    protomonPkt->chid = CEREBUS_SYSPACKET_CHANNEL;
    protomonPkt->type = cbPKTTYPE_SYSPROTOCOLMONITOR;
    protomonPkt->dlen = cbPKTDLEN_SYSPROTOCOLMONITOR;
    protomonPkt->sentpkts = pktsSent[0] - lastPktSentCount + 1;
    lastPktSentCount = pktsSent[0];
    lastPktSentClk = clk[0];

    pktSize[0] = (protomonPkt->dlen * 4) + cbPKT_HEADER_SIZE;
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
