/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Sep 27 14:00:04 2013
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <stdio.h> // memcpy
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void SampleSenderSimNSP2_Outputs_wrapper(const uint32_T *clk,
                          const int16_T *sampleData,
                          const int32_T *sampleNum,
                          const int32_T *numSamples,
                          const int32_T *running,
                          const int32_T *maxNumCbPkts,
                          uint8_T *udpData,
                          real_T *udpSize,
                          uint32_T *cbPkts)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/*
 * This code sends 'continuous data', ie samples. 
 * sampleData is block of continuous data samples, 
 * ordered this way assuming 96chs:
 * ch_1_samp_0, ch_2_samp_0, ch_3_samp_0 ... ch_96_samp_0,
 * ch_1_samp_1, ch_2_samp_1, ch_3_samp_1 ... ch_96_samp_1,
 * ch_1_samp_(numSamples-1) ... ch_96_(numSamples-1)
 *
 * sampleNum is the index of the sample in data block.  
 * note: count 1 sample per channel set
 *
 * N. Schmansky, Oct 2012
 */

#include <cbhwlib_lite.h>

static int udpDataIdx_NSP2 = 0;
static int unsigned cbPktCount_NSP2 = 0;
int ch;

// inputs:
static unsigned int sysclk_NSP2 = 0; // = clk[0];
short *data = (short*)&sampleData[0];
int dataIdx = sampleNum[0] * NUM_SIM_CHANNELS;
// maxNumCbPkts[0]

// outputs:
cbPKT_GROUP* contDataPkt; // = (cbPKT_GROUP*)&udpData[udpDataIdx];
udpSize[0] = 0; // don't output anything yet...
cbPkts[0] = 0;

// dont send anything if running flag is not set
if (running[0] == 0)
{
    return;
}

// initialize on first sample
if (sampleNum[0] == 0)
{
    sysclk_NSP2 = clk[0];
    udpDataIdx_NSP2 = 0;
    cbPktCount_NSP2 = 0;
}
contDataPkt = (cbPKT_GROUP*)&udpData[udpDataIdx_NSP2];

if (cbPktCount_NSP2 == 0)
{
    // clear the udp data buffer
    memset(udpData,0,2048); // 2048 = number of udpData bytes
}

// stuff up to five 'sample group' (continuous data) cerebus packets of 
// 30K data into a single UDP packet
contDataPkt->time = sysclk_NSP2++;
contDataPkt->chid = CEREBUS_GROUPPACKET_CHANNEL;
contDataPkt->type = 5; // sample group 5 is the 30K data
contDataPkt->dlen = NUM_SIM_CHANNELS/2; // 96 channels 
for (ch=1; ch<=NUM_SIM_CHANNELS; ch++)
{
    contDataPkt->data[ch-1] = data[dataIdx++];
}
udpDataIdx_NSP2 += (contDataPkt->dlen * 4) + cbPKT_HEADER_SIZE;

// now decide if the udp packet is filled enough to send
if ((++cbPktCount_NSP2 == maxNumCbPkts[0]) || // max number of cerebus pkts to fit in udp pkt
    (sampleNum[0] == (numSamples[0] - 1))) // last sample in sampleData[]
{
    cbPkts[0] = cbPktCount_NSP2;
    cbPktCount_NSP2 = 0;
    udpSize[0] = udpDataIdx_NSP2; // pkt gets sent when non-zero udpSize
    udpDataIdx_NSP2 = 0;
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
