/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Jul 26 17:47:39 2013
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <stdio.h> // memcpy
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void SpikeSenderSim_Outputs_wrapper(const uint32_T *clk,
                          const int32_T *spikeCounts,
                          const int32_T *chanNum,
                          const int32_T *numChans,
                          const int32_T *running,
                          uint8_T *udpData,
                          real_T *udpSize,
                          uint32_T *cbPkts)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/*
 * This code sends a spike packet for each spike that might have
 * occurred on a channel, as found in the spikeCounts array.
 * That is, spikeCounts[0] is the number spikes that happened on ch 1,
 * spikeCounts[1] is the number of spikes on ch 2.  
 * Since multiple cerebus spike packets can fit in a single UDP packet, we
 * fill a udp pkt with as many packets as we can fit in a standard UDP
 * packet and then send it (or send what we have if our for-loop is on
 * the last channel). 
 *
 * N. Schmansky, Dec 2012
 */

#include <cbhwlib_lite.h>

#define MAX_UDP_DATA_SIZE 1500  // actually its 1514 bytes

static int udpDataIdx;
static unsigned int cbPktCount;
int i;
cbPKT_SPK* spikePkt;

// dont send anything if running flag is not set
if (running[0] == 0)
{
    //udpData[0]=1;
    return;
}

// inputs:
// clk[0];
// spikeCounts[0];
// chanNum[0];   this is the forloop counter, which starts at zero
// numChans[0];  total number of channels, 1-based

// outputs:
udpSize[0] = 0; // don't output anything yet...when non-zero, udpData is sent
cbPkts[0] = 0; // number of spike pkts we've sent

// init vars on start of for loop
if (chanNum[0] == 0)
{
    cbPktCount = 0; // number spikes cumulative in for loop
    udpDataIdx = 0; // index into the udp data array
}

if (cbPktCount == 0)
{
    // clear the udp data buffer
    memset(udpData,0,2048); // 2048 = number of udpData bytes
}

// if there were are spikes on this channel, 
// then fill the udp packet with spike packet(s)
if (spikeCounts[chanNum[0]])
{
    for (i = 0; i < spikeCounts[chanNum[0]]; i++)
    {
        spikePkt = (cbPKT_SPK*)&udpData[udpDataIdx];

        // create spike packet
        spikePkt->time = clk[0]+i;
        spikePkt->chid = chanNum[0]+1;
        spikePkt->unit = 1; // unclassified unit
        spikePkt->dlen = 0;//cbPKTDLEN_SPKSHORT; // no waveform data
        
        udpDataIdx += (spikePkt->dlen * 4) + cbPKT_HEADER_SIZE;

        cbPktCount++; // update number of cerebus packets sent
    }
}

// if the udp packet is near its maximum capacity (full of cerebus spikes)
// or if we on the last channel
// then send it 
if ((udpDataIdx >= MAX_UDP_DATA_SIZE) || (chanNum[0] == (numChans[0]-1)))
{
    cbPkts[0] = cbPktCount;
    cbPktCount = 0;
    udpSize[0] = udpDataIdx; // udp pkt gets sent when non-zero udpSize
    udpDataIdx = 0; // start again with a fresh udp buffer

}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
