/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Mar 15 07:31:59 2013
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <windows.h>
#include <winbase.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void SysClock_30KHzSim_Outputs_wrapper(uint32_T *clk,
                          real_T *seconds)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/*
 * This code outputs a clock with 30 microsecond resolution (30KHz).
 * ie. the unsigned int it outputs increments 30000 times per second.
 *
 * N. Schmansky, March 2012
 */

static LARGE_INTEGER perfCounterStart;
static LARGE_INTEGER perfCounterFreq;
LARGE_INTEGER perfCounter;
double clkSeconds;

// so that clock output starts at 0
if ((perfCounterStart.HighPart == 0) &&
    (perfCounterStart.LowPart == 0)) // once only at startup
{
    QueryPerformanceCounter(&perfCounterStart);
}

// store the clock divisor (at startup only)
if ((perfCounterFreq.HighPart == 0) &&
    (perfCounterFreq.LowPart == 0)) // once only at startup
{
    QueryPerformanceFrequency(&perfCounterFreq); // gives us ticks per second
}

// read the hi-res clock
QueryPerformanceCounter(&perfCounter);

clkSeconds = ((double)(perfCounter.QuadPart - perfCounterStart.QuadPart) / 
              (double)perfCounterFreq.QuadPart);
seconds[0] = clkSeconds;
// output an unsigned int that increments 30000 times per second
clk[0] = (unsigned int)(clkSeconds * (double)30000);
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
