classdef GridMapGUI < handle
    
    properties
        hFigure
        guiHandles
    end % END properties
    
    properties(Access=private)
    end % END properties(Access=private)

    methods
        function this = GridMapGUI(varargin)
            layout(this);
        end % END function GridMapGUI
        
        function layout(this)
            
            textlbl_width = 150;
            editfld_width = 240;
            button_spc = 20;
            text_edit_spc = 20;
            
            base_font_sz = 12;
            title_font_sz = 16;
            
            % create the figure
            figpos = [50 100 1200 800];
            this.hFigure = figure(...
                'Position',figpos,...
                'PaperPositionMode','auto',...
                'NumberTitle','off',...
                'WindowKeyPressFcn',@(h,kp)keyPressHandler(this,kp),...
                'MenuBar','none','ToolBar','none');
            this.hFigure.CloseRequestFcn = @(src,dt)close(this);
            
            % create save/load buttons
            localHeight = 40;
            currLeft = 60;
            currBottom = 715;
            localWidth = 100;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','on',...
                'String','Load',...
                'HorizontalAlignment','left',...
                'Style','pushbutton',...
                'FontSize',title_font_sz,...
                'Tag','buttonLoadGridMap',...
                'TooltipString','Load a grid map',...
                'Callback',@(h,evt)buttonLoadGridMap_Callback(this));
            
            currLeft = currLeft + localWidth + button_spc;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','on',...
                'String','Save',...
                'HorizontalAlignment','left',...
                'Style','pushbutton',...
                'FontSize',title_font_sz,...
                'Tag','buttonSaveGridMap',...
                'TooltipString','Save the grid map',...
                'Callback',@(h,evt)buttonSaveGridMap_Callback(this));
            
            % create grid map listbox
            localHeight = 600;
            currLeft = 60;
            currBottom = 100;
            localWidth = 500;
            uicontrol(...
                'Parent',this.hFigure,...
                'enable','on',...
                'Position',[currLeft currBottom localWidth localHeight],...
                'String','0',...
                'FontSize',base_font_sz,...
                'FontWeight','bold',...
                'Style','listbox',...
                'Tag','listboxGridMap',...
                'Callback',@(h,evt)listboxGridMap_Callback(this));
            
            % create add/edit/delete buttons
            localHeight = 30;
            currLeft = 60;
            currBottom = 50;
            localWidth = 100;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','on',...
                'String','Add',...
                'HorizontalAlignment','left',...
                'Style','pushbutton',...
                'FontSize',base_font_sz,...
                'Tag','buttonAddGrid',...
                'TooltipString','Add a grid',...
                'Callback',@(h,evt)buttonAddGrid_Callback(this));
            
            currLeft = currLeft + localWidth + button_spc;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','on',...
                'String','Edit',...
                'HorizontalAlignment','left',...
                'Style','pushbutton',...
                'FontSize',base_font_sz,...
                'Tag','buttonEditGrid',...
                'TooltipString','Edit a grid',...
                'Callback',@(h,evt)buttonEditGrid_Callback(this));
            
            currLeft = currLeft + localWidth + button_spc;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','on',...
                'String','Delete',...
                'HorizontalAlignment','left',...
                'Style','pushbutton',...
                'FontSize',base_font_sz,...
                'Tag','buttonDeleteGrid',...
                'TooltipString','Delete a grid',...
                'Callback',@(h,evt)buttonDeleteGrid_Callback(this));
            
            
            
            % editing fields
            % template label/editbox
            currLeft = 700;
            currBottom = 670;
            localWidth = textlbl_width;
            localHeight = 30;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Template',...
                'HorizontalAlignment','left',...
                'Style','text',...
                'FontSize',base_font_sz,...
                'Tag','textTemplate');
            currLeft = currLeft + localWidth + text_edit_spc;
            localWidth = editfld_width;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom+4 localWidth localHeight],...
                'String',{'No Templates Available'},...
                'Enable','off',...
                'FontSize',base_font_sz,...
                'Style','popupmenu',...
                'Tag','popupTemplates',...
                'Callback',@(h,evt)popupTemplates_Callback(this));
            
            % brain label/editbox
            currLeft = 700;
            currBottom = 620;
            localWidth = textlbl_width;
            localHeight = 30;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Brain Area',...
                'HorizontalAlignment','left',...
                'Style','text',...
                'FontSize',base_font_sz,...
                'Tag','textBrainAreas');
            currLeft = currLeft + localWidth + text_edit_spc;
            localWidth = editfld_width;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom+4 localWidth localHeight],...
                'String',{'No Brain Areas Available'},...
                'Enable','off',...
                'FontSize',base_font_sz,...
                'Style','popupmenu',...
                'Tag','popupBrainAreas',...
                'Callback',@(h,evt)popupBrainAreas_Callback(this));
            
            % hemisphere label/editbox
            currLeft = 700;
            currBottom = 570;
            localWidth = textlbl_width;
            localHeight = 30;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Hemisphere',...
                'HorizontalAlignment','left',...
                'Style','text',...
                'FontSize',base_font_sz,...
                'Tag','textHemisphere');
            currLeft = currLeft + localWidth + text_edit_spc;
            localWidth = editfld_width;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom+4 localWidth localHeight],...
                'String',{'Left','Right','None'},...
                'Enable','off',...
                'FontSize',base_font_sz,...
                'Style','popupmenu',...
                'Tag','popupHemisphere',...
                'Callback',@(h,evt)popupHemisphere_Callback(this));
            
            % grid label label/editbox
            currLeft = 700;
            currBottom = 520;
            localWidth = textlbl_width;
            localHeight = 30;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Label',...
                'HorizontalAlignment','left',...
                'Style','text',...
                'FontSize',12,...
                'Tag','textLabel');
            currLeft = currLeft + localWidth + text_edit_spc;
            localWidth = editfld_width;
            uicontrol(...
                'Parent',this.hFigure,...
                'enable','off',...
                'FontSize',base_font_sz,...
                'HorizontalAlignment','left',...
                'Position',[currLeft currBottom+4 localWidth localHeight],...
                'String','[No Label Specified]',...
                'Style','edit',...
                'Tag','editLabel');
            
            % grid label label/editbox
            currLeft = 700;
            currBottom = 470;
            localWidth = textlbl_width;
            localHeight = 30;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Electrodes',...
                'HorizontalAlignment','left',...
                'Style','text',...
                'FontSize',base_font_sz,...
                'Tag','textElectrodes');
            currLeft = currLeft + localWidth + text_edit_spc;
            localWidth = editfld_width;
            uicontrol(...
                'Parent',this.hFigure,...
                'enable','off',...
                'FontSize',base_font_sz,...
                'HorizontalAlignment','left',...
                'Position',[currLeft currBottom+4 localWidth localHeight],...
                'String','[No Electrodes Specified]',...
                'Style','edit',...
                'Tag','editElectrodes');
            
            % central channels label label/editbox
            currLeft = 700;
            currBottom = 420;
            localWidth = textlbl_width;
            localHeight = 30;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Central Channels',...
                'HorizontalAlignment','left',...
                'Style','text',...
                'FontSize',base_font_sz,...
                'Tag','textCentralChannels');
            currLeft = currLeft + localWidth + text_edit_spc;
            localWidth = editfld_width;
            uicontrol(...
                'Parent',this.hFigure,...
                'enable','off',...
                'FontSize',12,...
                'HorizontalAlignment','left',...
                'Position',[currLeft currBottom+4 localWidth localHeight],...
                'String','[No Central Channels Specified]',...
                'Style','edit',...
                'Tag','editCentralChannels');
            
            % create save/reset/cancel buttons
            localHeight = 30;
            currLeft = 700;
            currBottom = 370;
            localWidth = 100;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Add',...
                'HorizontalAlignment','left',...
                'Style','pushbutton',...
                'FontSize',base_font_sz,...
                'Tag','buttonSaveGrid',...
                'TooltipString','Save this grid',...
                'Callback',@(h,evt)buttonSaveGrid_Callback(this));
            
            currLeft = currLeft + localWidth + button_spc;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Reset',...
                'HorizontalAlignment','left',...
                'Style','pushbutton',...
                'FontSize',base_font_sz,...
                'Tag','buttonResetGrid',...
                'TooltipString','Reset this grid',...
                'Callback',@(h,evt)buttonResetGrid_Callback(this));
            
            currLeft = currLeft + localWidth + button_spc;
            uicontrol(...
                'Parent',this.hFigure,...
                'Position',[currLeft currBottom localWidth localHeight],...
                'Enable','off',...
                'String','Cancel',...
                'HorizontalAlignment','left',...
                'Style','pushbutton',...
                'FontSize',base_font_sz,...
                'Tag','buttonCancelGrid',...
                'TooltipString','Cancel this grid',...
                'Callback',@(h,evt)buttonCancelGrid_Callback(this));
            
        end % END function layout
        
        function keyPressHandler(this,kp)
        end  % END function keyPressHandler
        
        function listboxGridMap_Callback(this)
        end % END function listboxGridMap_Callback
        
        function buttonAddGrid_Callback(this)
        end % END function buttonAddGrid_Callback
        
        function buttonEditGrid_Callback(this)
        end % END function buttonEditGrid_Callback
        
        function buttonDeleteGrid_Callback(this)
        end % END function buttonDeleteGrid_Callback
        
        function buttonLoadGridMap_Callback(this)
        end % END function buttonLoadGridMap_Callback
        
        function buttonSaveGridMap_Callback(this)
        end % END function buttonSaveGridMap_Callback
        
        function popupTemplates_Callback(this)
        end % END function popupTemplates_Callback
        
        function popupBrainAreas_Callback(this)
        end % END popupBrainAreas_Callback
        
        function buttonSaveGrid_Callback(this)
        end % END function buttonSaveGrid_Callback
        
        function buttonResetGrid_Callback(this)
        end % END function buttonResetGrid_Callback
        
        function buttonCancelGrid_Callback(this)
        end % END function buttonCancelGrid_Callback
        
        function close(this)
            delete(this);
        end % END function close
        
        function delete(this)
            delete(this.hFigure);
        end % END function delete
    end % END methods

end % END classdef GridMapGUI