
typeDataBinary = struct('trueText', 'ON', 'falseText', 'OFF');
typeDataParam1D = struct('dim', [1 1]);
typeDataParamVect5 = struct('dim', [5 1]);
typeDataParamVect2 = struct('dim', [2 1]);



clear guiDescriptor
% guiDescriptor = struct( ...
%     'parameterName', 'neuralGain', ...
%     'type', 'parameter', ...
%     'label', 'Neural Gain', ...
%     'typeData', typeDataParamVect2);

guiDescriptor = struct( ...
    'parameterName', 'gainK', ...
    'type', 'parameter', ...
    'label', 'Kalman Gain', ...
    'typeData', typeDataParamVect5);

guiDescriptor(end+1) = struct( ...
    'parameterName', 'scaleXk', ...
    'type', 'parameter', ...
    'label', 'Scale Xk', ...
    'typeData', typeDataParamVect5);

guiDescriptor(end+1) = struct( ...
    'parameterName', 'offsetXk', ...
    'type', 'parameter', ...
    'label', 'Offset Xk', ...
    'typeData', typeDataParamVect5);


fh = figure;
autoLayoutParamUIs(fh, guiDescriptor, tg, 'linuxTaskComplete');

%addDecoderDownload(fh, @loadDecoderXPC);
